;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; sql-icons.el - icon variable definitions
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;;  Author:        Peter D. Pezaris <pez@atlantic2.sbi.com>
;;  Maintainer:    sql-mode-help@atlantic2.sbi.com
;;  Version:       0.922 (beta)
;;  Last Modified: Mon Aug  7 19:48:31 1995
;;  Keywords:      isql fsql sql editing major-mode languages
;;
;;  Copyright © 1995 Peter D. Pezaris
;;
;;  This file is part of the SQL Mode package.  Refer to the sql-mode.el
;;  file for more details.
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defvar sql-top-ten-0-icon
  (toolbar-make-button-list "/* XPM */
static char * zero_xpm[] = {
\"28 28 2 1\",
\" 	c grey75\",
\".	c black\",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"           ......           \",
\"          ........          \",
\"         ..........         \",
\"        ....    ....        \",
\"        ...      ...        \",
\"       ....      ....       \",
\"       ...        ...       \",
\"       ...        ...       \",
\"       ...        ...       \",
\"       ...        ...       \",
\"       ...        ...       \",
\"       ...        ...       \",
\"       ...        ...       \",
\"       ...        ...       \",
\"       ....      ....       \",
\"        ...      ...        \",
\"        ....    ....        \",
\"         ..........         \",
\"          ........          \",
\"           ......           \",
\"                            \",
\"                            \",
\"                            \",
\"                            \"};")
  "Top ten #0 icon")


(defvar sql-top-ten-1-icon
  (toolbar-make-button-list "/* XPM */
static char * one_xpm[] = {
\"28 28 2 1\",
\" 	c grey75\",
\".	c black\",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"             ..             \",
\"          .....             \",
\"       ........             \",
\"       ........             \",
\"       .... ...             \",
\"            ...             \",
\"            ...             \",
\"            ...             \",
\"            ...             \",
\"            ...             \",
\"            ...             \",
\"            ...             \",
\"            ...             \",
\"            ...             \",
\"            ...             \",
\"            ...             \",
\"            ...             \",
\"       .............        \",
\"       .............        \",
\"       .............        \",
\"                            \",
\"                            \",
\"                            \",
\"                            \"};")
  "Top ten #1 icon")

(defvar sql-top-ten-2-icon
  (toolbar-make-button-list "/* XPM */
static char * two_xpm[] = {
\"28 28 2 1\",
\" 	c grey75\",
\".	c black\",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"           ......           \",
\"         ..........         \",
\"        ............        \",
\"       .....    ....        \",
\"       ....       ...       \",
\"       ...        ...       \",
\"                  ...       \",
\"                 ....       \",
\"                ....        \",
\"               .....        \",
\"              .....         \",
\"             .....          \",
\"            ....            \",
\"          .....             \",
\"         .....              \",
\"        .....     ...       \",
\"      .....       ...       \",
\"      ...............       \",
\"      ...............       \",
\"      ...............       \",
\"                            \",
\"                            \",
\"                            \",
\"                            \"};")
  "Top ten #2 icon")

(defvar sql-top-ten-3-icon
  (toolbar-make-button-list "/* XPM */
static char * three_xpm[] = {
\"28 28 2 1\",
\" 	c grey75\",
\".	c black\",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"          ......            \",
\"        ..........          \",
\"       ............         \",
\"       ....     ....        \",
\"       ...       ...        \",
\"                 ...        \",
\"                ....        \",
\"           ........         \",
\"           .......          \",
\"           ......           \",
\"                ...         \",
\"                 ...        \",
\"                  ...       \",
\"                  ...       \",
\"                  ...       \",
\"                 ....       \",
\"      ...       ....        \",
\"      ..............        \",
\"      .............         \",
\"        .........           \",
\"                            \",
\"                            \",
\"                            \",
\"                            \"};")
  "Top ten #3 icon")

(defvar sql-top-ten-4-icon
  (toolbar-make-button-list "/* XPM */
static char * four_xpm[] = {
\"28 28 2 1\",
\" 	c grey75\",
\".	c black\",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"              ....          \",
\"             .....          \",
\"             .....          \",
\"            ......          \",
\"            ......          \",
\"           .......          \",
\"           ... ...          \",
\"          ...  ...          \",
\"         ....  ...          \",
\"         ...   ...          \",
\"        ....   ...          \",
\"        ...    ...          \",
\"       .............        \",
\"       .............        \",
\"       .............        \",
\"               ...          \",
\"               ...          \",
\"            ........        \",
\"            ........        \",
\"            ........        \",
\"                            \",
\"                            \",
\"                            \",
\"                            \"};")
  "Top ten #4 icon")

(defvar sql-top-ten-5-icon
  (toolbar-make-button-list "/* XPM */
static char * five_xpm[] = {
\"28 28 2 1\",
\" 	c grey75\",
\".	c black\",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"        ............        \",
\"        ............        \",
\"        ............        \",
\"        ...                 \",
\"        ...                 \",
\"        ...                 \",
\"        ...                 \",
\"        ... .....           \",
\"        ...........         \",
\"        ............        \",
\"        ...     ....        \",
\"                 ....       \",
\"                  ...       \",
\"                  ...       \",
\"                  ...       \",
\"                 ....       \",
\"      ...       ....        \",
\"      ..............        \",
\"       ............         \",
\"         ........           \",
\"                            \",
\"                            \",
\"                            \",
\"                            \"};")
  "Top ten #5 icon")

(defvar sql-top-ten-6-icon
  (toolbar-make-button-list "/* XPM */
static char * six_xpm[] = {
\"28 28 2 1\",
\" 	c grey75\",
\".	c black\",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"              .....         \",
\"            ........        \",
\"          ..........        \",
\"         .....              \",
\"         ...                \",
\"        ...                 \",
\"        ... ....            \",
\"       ... .......          \",
\"       ............         \",
\"       .....   ....         \",
\"       ....     ....        \",
\"       ...       ...        \",
\"       ...       ...        \",
\"       ...       ...        \",
\"       ....      ...        \",
\"        ...     ....        \",
\"        ....    ...         \",
\"         ..........         \",
\"          ........          \",
\"           .....            \",
\"                            \",
\"                            \",
\"                            \",
\"                            \"};")
  "Top ten #6 icon")

(defvar sql-top-ten-7-icon
  (toolbar-make-button-list "/* XPM */
static char * seven_xpm[] = {
\"28 28 2 1\",
\" 	c grey75\",
\".	c black\",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"       .............        \",
\"       .............        \",
\"       .............        \",
\"       ...       ..         \",
\"       ...       ..         \",
\"                ...         \",
\"                ...         \",
\"                ..          \",
\"               ...          \",
\"               ...          \",
\"               ...          \",
\"              ...           \",
\"              ...           \",
\"              ...           \",
\"             ...            \",
\"             ...            \",
\"             ...            \",
\"            ...             \",
\"            ...             \",
\"            ...             \",
\"                            \",
\"                            \",
\"                            \",
\"                            \"};")
  "Top ten #7 icon")

(defvar sql-top-ten-8-icon
  (toolbar-make-button-list "/* XPM */
static char * eight_xpm[] = {
\"28 28 2 1\",
\" 	c grey75\",
\".	c black\",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"           ......           \",
\"         ..........         \",
\"        ............        \",
\"        ...      ....       \",
\"       ...        ...       \",
\"       ...        ...       \",
\"       ...        ...       \",
\"        ....    ....        \",
\"        ............        \",
\"          ........          \",
\"         ..........         \",
\"        ....    ....        \",
\"       ....      ....       \",
\"       ...        ...       \",
\"       ...        ...       \",
\"       ...        ...       \",
\"       .....    .....       \",
\"        ............        \",
\"         ..........         \",
\"           ......           \",
\"                            \",
\"                            \",
\"                            \",
\"                            \"};")
  "Top ten #8 icon")

(defvar sql-top-ten-9-icon
  (toolbar-make-button-list "/* XPM */
static char * nine_xpm[] = {
\"28 28 2 1\",
\" 	c grey75\",
\".	c black\",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"          ......            \",
\"         ........           \",
\"        ..........          \",
\"       ....    ....         \",
\"       ...      ...         \",
\"       ...       ...        \",
\"       ...       ...        \",
\"       ...      ....        \",
\"        ...    .....        \",
\"        ............        \",
\"         ....... ...        \",
\"           ....  ...        \",
\"                ....        \",
\"                ...         \",
\"               ....         \",
\"              ....          \",
\"       ..    ....           \",
\"       ..........           \",
\"       ........             \",
\"        .....               \",
\"                            \",
\"                            \",
\"                            \",
\"                            \"};")
  "Top ten #9 icon")

(defvar sql-separator-icon
  (toolbar-make-button-list "/* XPM */
static char * sep[] = {
\"12 28 1 1\",
\"X	c Gray75\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\",
\"XXXXXXXXXXXX\"};")
  "A separator icon list")

(defvar sql-go-icon
  (toolbar-make-button-list "/* XPM */
static char * go[] = {
\"28 28 3 1\",
\"X	c Gray75\",
\"o	c green3\",
\"O	c white\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXoooooooXXXXXXXXXXX\",
\"XXXXXXXXoooooooooooXXXXXXXXX\",
\"XXXXXXoooooooooooooooXXXXXXX\",
\"XXXXXoooooooooooooooooXXXXXX\",
\"XXXXoooooooooooooooooooXXXXX\",
\"XXXXoooooooooooooooooooXXXXX\",
\"XXXooooOOOOOoooooOOOooooXXXX\",
\"XXXooOOOOoOOOooOOOoOOOooXXXX\",
\"XXoooOOoooooOooOOoooOOoooXXX\",
\"XXooOOooooooooOOoooooOOooXXX\",
\"XXooOOooooooooOOoooooOOooXXX\",
\"XXooOOoooOOOOoOOoooooOOooXXX\",
\"XXooOOoooooOOoOOoooooOOooXXX\",
\"XXooOOoooooOOoOOoooooOOooXXX\",
\"XXoooOOooooOOooOOoooOOoooXXX\",
\"XXXooOOOOoOOOooOOOoOOOooXXXX\",
\"XXXooooOOOOoOooooOOOooooXXXX\",
\"XXXXoooooooooooooooooooXXXXX\",
\"XXXXoooooooooooooooooooXXXXX\",
\"XXXXXoooooooooooooooooXXXXXX\",
\"XXXXXXoooooooooooooooXXXXXXX\",
\"XXXXXXXXoooooooooooXXXXXXXXX\",
\"XXXXXXXXXXoooooooXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\"};")
  "A go icon list")

(defvar sql-abort-icon
  (toolbar-make-button-list "/* XPM */
static char * s2_xpm[] = {
\"28 28 3 1\",
\"X	c Gray75\",
\"o	c white\",
\"O	c red\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXoooooooooXXXXXXXXXX\",
\"XXXXXXXXoOOOOOOOOOoXXXXXXXXX\",
\"XXXXXXXoOOOOOOOOOOOoXXXXXXXX\",
\"XXXXXXoOOOOOOOOOOOOOoXXXXXXX\",
\"XXXXXoOOOOOOOOOOOOOOOoXXXXXX\",
\"XXXXoOOOOOOOOOOOOOOOOOoXXXXX\",
\"XXXoOOOOOOOOOOOOOOOOOOOoXXXX\",
\"XXoOOOooOOoooOOooOOooOOOoXXX\",
\"XXoOOoOOoOOoOOoOOoOoOoOOoXXX\",
\"XXoOOoOOOOOoOOoOOoOoOoOOoXXX\",
\"XXoOOoOOOOOoOOoOOoOoOoOOoXXX\",
\"XXoOOOooOOOoOOoOOoOoOoOOoXXX\",
\"XXoOOOOOoOOoOOoOOoOooOOOoXXX\",
\"XXoOOOOOoOOoOOoOOoOoOOOOoXXX\",
\"XXoOOoOOoOOoOOoOOoOoOOOOoXXX\",
\"XXoOOOooOOOoOOOooOOoOOOOoXXX\",
\"XXXoOOOOOOOOOOOOOOOOOOOoXXXX\",
\"XXXXoOOOOOOOOOOOOOOOOOoXXXXX\",
\"XXXXXoOOOOOOOOOOOOOOOoXXXXXX\",
\"XXXXXXoOOOOOOOOOOOOOoXXXXXXX\",
\"XXXXXXXoOOOOOOOOOOOoXXXXXXXX\",
\"XXXXXXXXoOOOOOOOOOoXXXXXXXXX\",
\"XXXXXXXXXoooooooooXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX..\;")
  "A stop icon list.")

(defvar sql-sp-lock-icon
  (toolbar-make-button-list "/* XPM */
static char * slock[] = {
\"28 28 5 1\",
\"X	c Gray75\",
\"o	c white\",
\"O	c #888888888888\",
\"+	c black\",
\"@	c Gray90\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXoooXXoXooXXXXXXXXXX\",
\"XXXXXXXXooXooXooXooXXXXXXXXX\",
\"XXXXXXXXXoooOOoo+XoXXXXXXXXX\",
\"XXXXXXXXX@OooOooO+oXXXXXXXXX\",
\"XXXXXXXXoo+oo+ooOooXXXXXXXXX\",
\"XXXXXXXX@oooXXooooO+XXXXXXXX\",
\"XXXXXXXX@O+XXXooX@O+XXXXXXXX\",
\"XXXXXXXX@O+XXXooX@O+XXXXXXXX\",
\"XXXXXXXX@O+XXXXXX@O+XXXXXXXX\",
\"XXXXXXX@@@@@@@@@@@@@+XXXXXXX\",
\"XXXXXXX@OOOOOOOOOOOO+XXXXXXX\",
\"XXXXXXX@OOOOOOOOOOOO+XXXXXXX\",
\"XXXXXXX@OOOOOOOOOOOO+XXXXXXX\",
\"XXXXXXX@OOOOOOOOOOOO+XXXXXXX\",
\"XXXXXXX@OOOOOOOOOOOO+XXXXXXX\",
\"XXXXXXX@OOOOOOOOOOOO+XXXXXXX\",
\"XXXXXXX@OOOOOOOOOOOO+XXXXXXX\",
\"XXXXXXX@OOOOOOOOOOOO+XXXXXXX\",
\"XXXXXXX++++++++++++++XXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\"};")
  "A sp_lock icon list.")

(defvar sql-sp-who-icon
  (toolbar-make-button-list "/* XPM */
static char * swho[] = {
\"28 28 4 1\",
\"X	c Gray75\",
\"o	c white\",
\"O	c black\",
\"+	c #888888888888\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXoooXXoXooXXXXXXXXXX\",
\"XXXXXXXXooXooXooXooXXXXXXXXX\",
\"XXXXXXXXXoooXXooXXoXXXXXXXXX\",
\"XXXXXXXXXXXooXooXXoXXXXXXXXX\",
\"XXXXXXXXooXooXooXooXXXXXXXXX\",
\"XXXXXXXXXoooXXooooXXXXXXXXXX\",
\"XXXXXXXXXXXXXXooXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXooXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXOOXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXOOXXXXXXXXXXXXXX\",
\"XXXXOOXOXOOXOOOOXXXOOOXXXXXX\",
\"XXXXOOXOXOOXOO+OOXOO+OOXXXXX\",
\"XXXXOO+O+OOXOOXOOXOOXOOXXXXX\",
\"XXXXXOO+OOXXOOXOOXOOXOOXXXXX\",
\"XXXXXOOXOOXXOOXOOXOO+OOXXXXX\",
\"XXXXXOOXOOXXOOXOOXXOOOXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\"};")
  "A sp_who icon list.")

(defvar sql-sp-what-icon
  (toolbar-make-button-list "/* XPM */
static char * swht[] = {
\"28 28 4 1\",
\"X	c Gray75\",
\"o	c white\",
\"O	c black\",
\"+	c #888888888888\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXoooXXoXooXXXXXXXXXX\",
\"XXXXXXXXooXooXooXooXXXXXXXXX\",
\"XXXXXXXXXoooXXooXXoXXXXXXXXX\",
\"XXXXXXXXXXXooXooXXoXXXXXXXXX\",
\"XXXXXXXXooXooXooXooXXXXXXXXX\",
\"XXXXXXXXXoooXXooooXXXXXXXXXX\",
\"XXXXXXXXXXXXXXooXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXooXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXOOXXXXXXXXXXOOXXXX\",
\"XXXXXXXXXXOOXXXXXXXXXXOOXXXX\",
\"XXOOXOXOOXOOOOXXXOOOXXOOOXXX\",
\"XXOOXOXOOXOO+OOXOX+OOXOOXXXX\",
\"XXOO+O+OOXOOXOOXXOOOOXOOXXXX\",
\"XXXOO+OOXXOOXOOXOOXOOXOOXXXX\",
\"XXXOOXOOXXOOXOOXOO+OOXOOXXXX\",
\"XXXOOXOOXXOOXOOXXOOXOOXOOXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\"};")
  "A sp_what icon list.")

(defvar sql-new-query-icon
  (toolbar-make-button-list "/* XPM */
static char * undo[] = {
\"28 28 5 1\",
\"X	c Gray75\",
\"o	c black\",
\"O	c Gray60\",
\"+	c Gray90\",
\"@	c white\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXooXXXXXXX\",
\"XXXXXXXXXXXXXXXXXooOOooooXXX\",
\"XXXXXXXXXXXXXXXooOOOOOOOOooX\",
\"XXXXXXXXXXXXXooOOOOOOOOOooXX\",
\"XXXXXXXXXXXoo++ooooOOOooOoXX\",
\"XXXXXXXXXoo++++++++oooOOoXXX\",
\"XXXXXXXoo+++++++++oooOOOoXXX\",
\"XXXXXoo+++++++++oo++oOOoXXXX\",
\"XXXXoo++++++++oo+++oOooXXXXX\",
\"XXXo++oooo++oo+++++ooXXXXXXX\",
\"XXXo++++++oo+++++ooXXXXXXXXX\",
\"XXo+++++++o++++ooXXXXXXXXXXX\",
\"XXo+++++++o++ooXXXXXXXXXXXXX\",
\"Xoo++++++o+ooXXXXXXXXXXXXXXX\",
\"X@@oooo++ooXXXXXXXXXXXXXXXXX\",
\"X@@@@@@ooXXXXXXXXXXXXXXXXXXX\",
\"X@@@@@@XXXXXXXXXXXXXXXXXXXXX\",
\"X@@@@XXXXXXXXXXXXXXXXXXXXXXX\",
\"X@@@XXXXXXXXXXXXXXXXXXXXXXXX\",
\"X@XXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\"};")
  "A new icon list.")

(defvar sql-previous-icon
  (toolbar-make-button-list "/* XPM */
static char * rev[] = {
\"28 28 4 1\",
\"X	c Gray75\",
\"o	c #888888888888\",
\"O	c #989898989898\",
\"+	c black\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXoOOXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXO++++oOXXXXXXXXXXXXXXXXXX\",
\"XXXO++++++++oOXXXXXXXXXXXXXX\",
\"XXXX++++++++++++oOXXXXXXXXXX\",
\"XXXX++++++++++++++++XXXXXXXX\",
\"XXXXo++++++++++++++XXXXXXXXX\",
\"XXXXO+++++++++++++XXXXXXXXXX\",
\"XXXXX++++++++++++XXXXXXXXXXX\",
\"XXXXX+++++++++++XXXXXXXXXXXX\",
\"XXXXXo+++++++++++XXXXXXXXXXX\",
\"XXXXXO++++++++++++XXXXXXXXXX\",
\"XXXXXX+++++++++++++XXXXXXXXX\",
\"XXXXXX++++++++++++++XXXXXXXX\",
\"XXXXXXo++++X+++++++++XXXXXXX\",
\"XXXXXXO+++XXX+++++++++XXXXXX\",
\"XXXXXXX++XXXXX+++++++++XXXXX\",
\"XXXXXXX+XXXXXXX+++++++++XXXX\",
\"XXXXXXXXXXXXXXXX+++++++XXXXX\",
\"XXXXXXXXXXXXXXXXX+++++XXXXXX\",
\"XXXXXXXXXXXXXXXXXX+++XXXXXXX\",
\"XXXXXXXXXXXXXXXXXXX+XXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\"};")
  "A previous icon list.")

(defvar sql-next-icon
  (toolbar-make-button-list "/* XPM */
static char * nt[] = {
\"28 28 4 1\",
\"X	c Gray75\",
\"o	c black\",
\"O	c #989898989898\",
\"+	c #888888888888\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXoXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXoooXXXXXXXXXXXXXXXXXX\",
\"XXXXXXoooooXXXXXXXXXXXXXXXXX\",
\"XXXXXoooooooXXXXXXXXXXXXXXXX\",
\"XXXXoooooooooXXXXXXXoXXXXXXX\",
\"XXXXXoooooooooXXXXXooXXXXXXX\",
\"XXXXXXoooooooooXXXoooOXXXXXX\",
\"XXXXXXXoooooooooXoooo+XXXXXX\",
\"XXXXXXXXooooooooooooooXXXXXX\",
\"XXXXXXXXXoooooooooooooXXXXXX\",
\"XXXXXXXXXXooooooooooooOXXXXX\",
\"XXXXXXXXXXXooooooooooo+XXXXX\",
\"XXXXXXXXXXXXoooooooooooXXXXX\",
\"XXXXXXXXXXXooooooooooooXXXXX\",
\"XXXXXXXXXXoooooooooooooOXXXX\",
\"XXXXXXXXXoooooooooooooo+XXXX\",
\"XXXXXXXXooooooooooooooooXXXX\",
\"XXXXXXXXXXO+ooooooooooooXXXX\",
\"XXXXXXXXXXXXXXO+ooooooooOXXX\",
\"XXXXXXXXXXXXXXXXXXO+ooooOXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXOO+XXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\"};")
  "An next icon list.")

(defvar sql-previous-global-icon
  (toolbar-make-button-list "/* XPM */
static char * rev[] = {
\"28 28 4 1\",
\"X	c Gray75\",
\"o	c #888888888888\",
\"O	c #989898989898\",
\"+	c blue\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXoOOXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXO++++oOXXXXXXXXXXXXXXXXXX\",
\"XXXO++++++++oOXXXXXXXXXXXXXX\",
\"XXXX++++++++++++oOXXXXXXXXXX\",
\"XXXX++++++++++++++++XXXXXXXX\",
\"XXXXo++++++++++++++XXXXXXXXX\",
\"XXXXO+++++++++++++XXXXXXXXXX\",
\"XXXXX++++++++++++XXXXXXXXXXX\",
\"XXXXX+++++++++++XXXXXXXXXXXX\",
\"XXXXXo+++++++++++XXXXXXXXXXX\",
\"XXXXXO++++++++++++XXXXXXXXXX\",
\"XXXXXX+++++++++++++XXXXXXXXX\",
\"XXXXXX++++++++++++++XXXXXXXX\",
\"XXXXXXo++++X+++++++++XXXXXXX\",
\"XXXXXXO+++XXX+++++++++XXXXXX\",
\"XXXXXXX++XXXXX+++++++++XXXXX\",
\"XXXXXXX+XXXXXXX+++++++++XXXX\",
\"XXXXXXXXXXXXXXXX+++++++XXXXX\",
\"XXXXXXXXXXXXXXXXX+++++XXXXXX\",
\"XXXXXXXXXXXXXXXXXX+++XXXXXXX\",
\"XXXXXXXXXXXXXXXXXXX+XXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\"};")
  "A previous icon list.")

(defvar sql-next-global-icon
  (toolbar-make-button-list "/* XPM */
static char * nt[] = {
\"28 28 4 1\",
\"X	c Gray75\",
\"o	c blue\",
\"O	c #989898989898\",
\"+	c #888888888888\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXoXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXoooXXXXXXXXXXXXXXXXXX\",
\"XXXXXXoooooXXXXXXXXXXXXXXXXX\",
\"XXXXXoooooooXXXXXXXXXXXXXXXX\",
\"XXXXoooooooooXXXXXXXoXXXXXXX\",
\"XXXXXoooooooooXXXXXooXXXXXXX\",
\"XXXXXXoooooooooXXXoooOXXXXXX\",
\"XXXXXXXoooooooooXoooo+XXXXXX\",
\"XXXXXXXXooooooooooooooXXXXXX\",
\"XXXXXXXXXoooooooooooooXXXXXX\",
\"XXXXXXXXXXooooooooooooOXXXXX\",
\"XXXXXXXXXXXooooooooooo+XXXXX\",
\"XXXXXXXXXXXXoooooooooooXXXXX\",
\"XXXXXXXXXXXooooooooooooXXXXX\",
\"XXXXXXXXXXoooooooooooooOXXXX\",
\"XXXXXXXXXoooooooooooooo+XXXX\",
\"XXXXXXXXooooooooooooooooXXXX\",
\"XXXXXXXXXXO+ooooooooooooXXXX\",
\"XXXXXXXXXXXXXXO+ooooooooOXXX\",
\"XXXXXXXXXXXXXXXXXXO+ooooOXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXOO+XXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\"};")
  "An next icon list.")

(defvar sql-top-ten-icon
  (toolbar-make-button-list "/* XPM */
static char * tt[] = {
\"28 28 4 1\",
\"X	c Gray75\",
\"o	c #888888888888\",
\"O	c black\",
\"+	c white\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXoOOooXXXXXXXXX\",
\"XXXXXXXXXXXXXOOOOOOooXXXXXXX\",
\"XXXXXXXXXXXXoOOOOOOOOooXXXXX\",
\"XXXXXXXXXXXXOOOOOOOOOOOXXXXX\",
\"XXXXXXXXXXXXOOOOOOOOOOOOXXXX\",
\"XXXXXXXXXXXoOOOOOOOOOOOOoXXX\",
\"XXXXXXXXXXXOOOOOOOOOOOOOOXXX\",
\"XXXXXXXXXXOOOOOOOOOOOOOOOXXX\",
\"XXXXXXXo+++++OOOOOOOOOOOoXXX\",
\"XXXXXoOOOOOO++++OOOOOOOXXXXX\",
\"XXXXOOOOOOOOOOOO+OOOOOXXXXXX\",
\"XXXXOOOOOOOOOOOOO++OOXXXXXXX\",
\"XXXXoOOOOOOOOOOOOOO+OXXXXXXX\",
\"XXXXXOOOO++OO++++OOO+XXXXXXX\",
\"XXXXXXo++++O++OO++OOOXXXXXXX\",
\"XXXXXXXXO++O++OO++OOOoXXXXXX\",
\"XXXXXXXXX++O++OO++OOOOXXXXXX\",
\"XXXXXXXXX++O++OO++OOOOXXXXXX\",
\"XXXXXXXXX++X++OO++OOoXXXXXXX\",
\"XXXXXXXXX++X++XX++XXXXXXXXXX\",
\"XXXXXXXXX++X++XX++XXXXXXXXXX\",
\"XXXXXXXXX++XX++++XXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\"};")
  "A top-ten icon list.")

(defvar sql-insert-file-icon
  (toolbar-make-button-list "/* XPM */
static char * file[] = {
\"28 28 4 1\",
\"X	c Gray75\",
\"o	c black\",
\"O	c white\",
\"+	c Gray60\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXooooooooooooXXXXXXXXXX\",
\"XXXXXXoOOOOOOOOOOooXXXXXXXXX\",
\"XXXXXXoOOOOOOOOOOo+oXXXXXXXX\",
\"XXXXXXoOOOOOOOOOOo++oXXXXXXX\",
\"XXXXXXoOOOOOOOOOOoooooXXXXXX\",
\"XXXXXXoOOOOOOOOOOOOOOoXXXXXX\",
\"XXXXXXoOOOOOOOOOOOOOOoXXXXXX\",
\"XXXXXXoOOOOOOOOOOOOOOoXXXXXX\",
\"XXXXXXoOOOOOOOOOOOOOOoXXXXXX\",
\"XXXXXXoOOOOOOOOOOOOOOoXXXXXX\",
\"XXXXXXoOOOOOOOOOOOOOOoXXXXXX\",
\"XXXXXXoOOOOOOOOOOOOOOoXXXXXX\",
\"XXXXXXoOOOOOOOOOOOOOOoXXXXXX\",
\"XXXXXXoOOOOOOOOOOOOOOoXXXXXX\",
\"XXXXXXoOOOOOOOOOOOOOOoXXXXXX\",
\"XXXXXXoOOOOOOOOOOOOOOoXXXXXX\",
\"XXXXXXoOOOOOOOOOOOOOOoXXXXXX\",
\"XXXXXXooooooooooooooooXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\"};")
  "A insert file icon list.")

(defvar sql-load-sp-icon
  (toolbar-make-button-list "/* XPM */
static char * file[] = {
\"28 28 4 1\",
\"X	c Gray75\",
\"o	c black\",
\"O	c white\",
\"+	c Gray60\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXooooooooooooXXXXXXXXXX\",
\"XXXXXXoOOOOOOOOOOooXXXXXXXXX\",
\"XXXXXXoOOOOOOOOOOo+oXXXXXXXX\",
\"XXXXXXoOOOOOOOOOOo++oXXXXXXX\",
\"XXXXXXoOOOOOOOOOOoooooXXXXXX\",
\"XXXXXXoOOOOOOOOOOOOOOoXXXXXX\",
\"XXXXXXoOOOOOOOOOOOOOOoXXXXXX\",
\"XXXXXXoOOoooOOoOooOOOoXXXXXX\",
\"XXXXXXoOooOooOooOooOOoXXXXXX\",
\"XXXXXXoOOoooOOooOOoOOoXXXXXX\",
\"XXXXXXoOOOOooOooOOoOOoXXXXXX\",
\"XXXXXXoOooOooOooOooOOoXXXXXX\",
\"XXXXXXoOOoooOOooooOOOoXXXXXX\",
\"XXXXXXoOOOOOOOooOOOOOoXXXXXX\",
\"XXXXXXoOOOOOOOooOOOOOoXXXXXX\",
\"XXXXXXoOOOOOOOOOOOOOOoXXXXXX\",
\"XXXXXXoOOOOOOOOOOOOOOoXXXXXX\",
\"XXXXXXooooooooooooooooXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\"};")
  "A load stored procedure icon list.")

(defvar sql-help-icon
  (toolbar-make-button-list "/* XPM */
static char * q[] = {
\"28 28 3 1\",
\"X	c Gray75\",
\"o	c #888888888888\",
\"O	c black\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXoOOOOoXXXXXXXXXXX\",
\"XXXXXXXXXoOOOOOOOOXXXXXXXXXX\",
\"XXXXXXXXXOOOOooOOOoXXXXXXXXX\",
\"XXXXXXXXoOOOXXXoOOOXXXXXXXXX\",
\"XXXXXXXXOOOXXXXXOOOXXXXXXXXX\",
\"XXXXXXXXOOOXXXXoOOoXXXXXXXXX\",
\"XXXXXXXXXXXXXXXOOOXXXXXXXXXX\",
\"XXXXXXXXXXXXXXOOOOXXXXXXXXXX\",
\"XXXXXXXXXXXXXOOOOXXXXXXXXXXX\",
\"XXXXXXXXXXXXXOOOXXXXXXXXXXXX\",
\"XXXXXXXXXXXXoOOoXXXXXXXXXXXX\",
\"XXXXXXXXXXXXOOOXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXOOOXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXOOOXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXoOoXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXOOOXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXoOoXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\"};")
  "A help icon list.")

(defvar sql-scroll-down-icon
  (toolbar-make-button-list "/* XPM */
static char * d[] = {
\"28 28 2 1\",
\"X	c Gray75\",
\"o	c blue\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXoooooooXXXXXXXXXX\",
\"XXXXXXXXXXXoooooooXXXXXXXXXX\",
\"XXXXXXXXXXXoooooooXXXXXXXXXX\",
\"XXXXXXXXXXXoooooooXXXXXXXXXX\",
\"XXXXXXXXXXXoooooooXXXXXXXXXX\",
\"XXXXXXXXXXXoooooooXXXXXXXXXX\",
\"XXXXXXXXXXXoooooooXXXXXXXXXX\",
\"XXXXXXXXXXXoooooooXXXXXXXXXX\",
\"XXXXXXXXXXXoooooooXXXXXXXXXX\",
\"XXXXXXoooooooooooooooooXXXXX\",
\"XXXXXXXoooooooooooooooXXXXXX\",
\"XXXXXXXXoooooooooooooXXXXXXX\",
\"XXXXXXXXXoooooooooooXXXXXXXX\",
\"XXXXXXXXXXoooooooooXXXXXXXXX\",
\"XXXXXXXXXXXoooooooXXXXXXXXXX\",
\"XXXXXXXXXXXXoooooXXXXXXXXXXX\",
\"XXXXXXXXXXXXXoooXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXoXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\"};")
  "A down icon list.")

(defvar sql-scroll-left-icon
  (toolbar-make-button-list "/* XPM */
static char * l[] = {
\"28 28 2 1\",
\"X	c Gray75\",
\"o	c blue\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXoXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXooXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXoooXXXXXXXXXXXXXX\",
\"XXXXXXXXXXooooXXXXXXXXXXXXXX\",
\"XXXXXXXXXoooooXXXXXXXXXXXXXX\",
\"XXXXXXXXoooooooooooooooXXXXX\",
\"XXXXXXXooooooooooooooooXXXXX\",
\"XXXXXXoooooooooooooooooXXXXX\",
\"XXXXXooooooooooooooooooXXXXX\",
\"XXXXXXoooooooooooooooooXXXXX\",
\"XXXXXXXooooooooooooooooXXXXX\",
\"XXXXXXXXoooooooooooooooXXXXX\",
\"XXXXXXXXXoooooXXXXXXXXXXXXXX\",
\"XXXXXXXXXXooooXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXoooXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXooXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXoXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\"};")
  "A left icon list.")

(defvar sql-scroll-right-icon
  (toolbar-make-button-list "/* XPM */
static char * r[] = {
\"28 28 2 1\",
\"X	c Gray75\",
\"o	c blue\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXoXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXooXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXoooXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXooooXXXXXXXXXX\",
\"XXXXXXXXXXXXXXoooooXXXXXXXXX\",
\"XXXXXoooooooooooooooXXXXXXXX\",
\"XXXXXooooooooooooooooXXXXXXX\",
\"XXXXXoooooooooooooooooXXXXXX\",
\"XXXXXooooooooooooooooooXXXXX\",
\"XXXXXoooooooooooooooooXXXXXX\",
\"XXXXXooooooooooooooooXXXXXXX\",
\"XXXXXoooooooooooooooXXXXXXXX\",
\"XXXXXXXXXXXXXXoooooXXXXXXXXX\",
\"XXXXXXXXXXXXXXooooXXXXXXXXXX\",
\"XXXXXXXXXXXXXXoooXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXooXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXoXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\"};")
  "A right info icon list.")

(defvar sql-scroll-up-icon
  (toolbar-make-button-list "/* XPM */
static char * u[] = {
\"28 28 2 1\",
\"X	c Gray75\",
\"o	c blue\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXoXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXoooXXXXXXXXXXXXX\",
\"XXXXXXXXXXXoooooXXXXXXXXXXXX\",
\"XXXXXXXXXXoooooooXXXXXXXXXXX\",
\"XXXXXXXXXoooooooooXXXXXXXXXX\",
\"XXXXXXXXoooooooooooXXXXXXXXX\",
\"XXXXXXXoooooooooooooXXXXXXXX\",
\"XXXXXXoooooooooooooooXXXXXXX\",
\"XXXXXoooooooooooooooooXXXXXX\",
\"XXXXXXXXXXoooooooXXXXXXXXXXX\",
\"XXXXXXXXXXoooooooXXXXXXXXXXX\",
\"XXXXXXXXXXoooooooXXXXXXXXXXX\",
\"XXXXXXXXXXoooooooXXXXXXXXXXX\",
\"XXXXXXXXXXoooooooXXXXXXXXXXX\",
\"XXXXXXXXXXoooooooXXXXXXXXXXX\",
\"XXXXXXXXXXoooooooXXXXXXXXXXX\",
\"XXXXXXXXXXoooooooXXXXXXXXXXX\",
\"XXXXXXXXXXoooooooXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\"};")
  "An up info icon list.")

(defvar sql-printer-icon
  (toolbar-make-button-list "/* XPM */
static char * printer[] = {
\"28 28 6 1\",
\"X	c Gray75\",
\"o	c black\",
\"O	c white\",
\"+	c Gray60\",
\"@	c Gray90\",
\"#	c Gray40\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXoooooooooXXXXXXXXXXXXX\",
\"XXXXXXoOOOOOOOooXXXXXXXXXXXX\",
\"XXXXXXoOooooOOoXoXXXXXXXXXXX\",
\"XXXXXXoOOOOOOOoooooooXXXXXXX\",
\"XXXXXXoOoooOOOOOOoXo+ooXXXXX\",
\"XXXXXXoOOOOOOOOOOoo++++oXXXX\",
\"XXXXXXoooooooooooo++++ooXXXX\",
\"XXXXXo@@@@@@@@@@@o+++o+oXXXX\",
\"XXXXo@@@@@@@@@@@@@o+o++oXXXX\",
\"XXXooooooooooooooooo+++oXXXX\",
\"XXXo@@@@@@@@@@@@@@@o+++oXXXX\",
\"XXXo@@@@@@@@@@@@@@@o++ooXXXX\",
\"XXXo@@@@@@@@@@@@@@@o+ooXXXXX\",
\"XXXo@@@@@@@@@@@@@@@oo#oXXXXX\",
\"XXXooooooooooooooooo#oXXXXXX\",
\"XXXXoXXXXXXXXXXXXXo#oXXXXXXX\",
\"XXXXXoXXXXXXXXXXXo#oXXXXXXXX\",
\"XXXXXoXXXXXXXXXXXooXXXXXXXXX\",
\"XXXXXXooooooooooooXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\",
\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\"};")
  "A printer icon list.")

(defvar sql-bcp-in-icon
  (toolbar-make-button-list "/* XPM */
static char * bcp-in_xpm[] = {
\"28 28 8 1\",
\" 	c grey75\",
\".	c red\",
\"X	c grey50\",
\"o	c black\",
\"O	c grey30\",
\"+	c grey40\",
\"@	c grey65\",
\"#	c white\",
\"                            \",
\"                 .          \",
\"    ....        ..          \",
\"    ......      ..          \",
\"   ........    ...          \",
\"  ........... .....         \",
\"  .................         \",
\" ..................XXXX     \",
\"       ............XXXXXX   \",
\"          .........XXXXXXX  \",
\"          ..........XXXXXo  \",
\"         ...........XXXOoo  \",
\"        ............+OOOoo  \",
\"       .............+OOOoo  \",
\"            ........+OOOoo  \",
\"              @@XX+++OOOoo  \",
\"              @@XX+++OOOoo  \",
\"              @@XX+++OOOoo  \",
\"              @@XX+++OOOoo  \",
\"   ######   ####X######Ooo  \",
\"    ##  ## ## @##X##+O##oo  \",
\"    ##  ## ## @##X##+O##oo  \",
\"    #####  ## @@XX##+O##oo  \",
\"    ##  ## ## @@XX#####Ooo  \",
\"    ##  ## ##  ##X##+OOOo   \",
\"    ##  ## ##  ##X##+OO     \",
\"   ######   #### #####      \",
\"                            \"};")
  "A bcp in icon list.")

(defvar sql-bcp-out-icon
  (toolbar-make-button-list "/* XPM */
static char * bcp-out_xpm[] = {
\"28 28 8 1\",
\" 	c grey75\",
\".	c red\",
\"X	c grey50\",
\"o	c black\",
\"O	c grey30\",
\"+	c grey40\",
\"@	c grey65\",
\"#	c white\",
\"                            \",
\" ########                   \",
\" #############              \",
\" ############               \",
\" ###########                \",
\" ##########                 \",
\"  #########                 \",
\"  ############   XXXXXX     \",
\"  ##################XXXXX   \",
\"  #################XXXXXXX  \",
\"  ##### ###########XXXXXXo  \",
\"   ###    ########XXXXXOoo  \",
\"   ##      ######X+++OOOoo  \",
\"   ##        ####X+++OOOoo  \",
\"   #          @@XX+++OOOoo  \",
\"              @@XX+++OOOoo  \",
\"              @@XX+++OOOoo  \",
\"              @@XX+++OOOoo  \",
\"              @@XX+++OOOoo  \",
\"   ######   ####X######Ooo  \",
\"    ##  ## ## @##X##+O##oo  \",
\"    ##  ## ## @##X##+O##oo  \",
\"    #####  ## @@XX##+O##oo  \",
\"    ##  ## ## @@XX#####Ooo  \",
\"    ##  ## ##  ##X##+OOOo   \",
\"    ##  ## ##  ##X##+OO     \",
\"   ######   #### #####      \",
\"                            \"};")
  "A bcp out icon list.")

(defvar sql-insert-row-icon
  (toolbar-make-button-list "/* XPM */
static char * insert-row_xpm[] = {
\"28 28 3 1\",
\" 	c grey75\",
\".	c red\",
\"X	c blue\",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"  .                         \",
\" ..    .                    \",
\"....  ..                    \",
\".... ...                    \",
\"  .......XXXXXXXXXXXXXX     \",
\"   ......XXXXXXXXXXXXXX     \",
\"    ......                  \",
\"    ......                  \",
\"   ....                     \",
\"   . XXXXXXXXXXXXXXXXXX     \",
\"     XXXXXXXXXXXXXXXXXX     \",
\"                            \",
\"                            \",
\"                            \",
\"     XXXXXXXXXXXXXXXXXX     \",
\"     XXXXXXXXXXXXXXXXXX     \",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"                            \"};")
  "An insert row icon list.")

(defvar sql-delete-row-icon
  (toolbar-make-button-list "/* XPM */
static char * delete-row_xpm[] = {
\"28 28 3 1\",
\" 	c grey75\",
\".	c blue\",
\"X	c red\",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"     ..................     \",
\"     ..................     \",
\"           X    X           \",
\"          XXX  XXX          \",
\"           XXXXXX           \",
\"     .......XXXX.......     \",
\"     .......XXXX.......     \",
\"           XXXXXX           \",
\"          XXX  XXX          \",
\"           X    X           \",
\"     ..................     \",
\"     ..................     \",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"                            \"};")
  "A delete row icon list.")

(defvar sql-update-row-icon
  (toolbar-make-button-list "/* XPM */
static char * update-row_xpm[] = {
\"28 28 4 1\",
\" 	c grey75\",
\".	c white\",
\"X	c red\",
\"o	c blue\",
\"                            \",
\"              ....          \",
\"         XX    ......       \",
\"        XX     .......      \",
\"       XX      ....         \",
\"      XX      ......        \",
\"      X       ..  ..        \",
\"     XX           ...       \",
\"     XXoooooooooooo..oo     \",
\"     XXoooooooooooo..oo     \",
\"     XXX   X      ..        \",
\"      XXX XX      ..        \",
\"       XXXXX      .         \",
\"     oooXXXXooooo..oooo     \",
\"     ooXXXXXXoo...ooooo     \",
\"      XXXXXXX  .            \",
\"         XXXXX              \",
\"                            \",
\"     oooooooooooooooooo     \",
\"     oooooooooooooooooo     \",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"                            \"};")
  "An update row icon list.")

;(defvar sql-frame-icon
;  (make-glyph "

(defvar sql-cut-icon
  (toolbar-make-button-list "/* XPM */
static char * sql-cut-red_xpm[] = {
\"28 28 8 1\",
\" 	s backgroundToolBarColor	c Gray75\",
\".	c red\",
\"X	c grey50\",
\"o	c grey65\",
\"O	c black\",
\"+	c grey30\",
\"@	c grey40\",
\"#	c white\",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"     .....                  \",
\"    ..   ..      XXXXXX     \",
\"   ..     ..   XXXXXXX...   \",
\"   .       .  XXXXXX......  \",
\"   ..     ... oXXX......XO  \",
\"    ..   .....ooX.....X+OO  \",
\"     .....   ......@@+++OO  \",
\"              .#.X@@@+++OO  \",
\"     .....   ......@@+++OO  \",
\"    ..   .....ooX.....++OO  \",
\"   ..     ... ooXX......OO  \",
\"   .       .  ooXX@@......  \",
\"   ..     ..  ooXX@@@+...O  \",
\"    ..   ..   ooXX@@@+++OO  \",
\"     .....    ooXX@@@+++OO  \",
\"              ooXX@@@+++OO  \",
\"              ooXX@@@+++OO  \",
\"              ooXX@@@+++OO  \",
\"               oXX@@@+++O   \",
\"                 X@@@++     \",
\"                            \",
\"                            \"};
")
  "A cut icon list.")

(defvar sql-copy-icon
  (toolbar-make-button-list "/* XPM */
static char * sql-copy_xpm[] = {
\"28 28 7 1\",
\" 	s backgroundToolBarColor	c Gray75\",
\".	c Gray60\",
\"X	c white\",
\"o	c grey50\",
\"O	c black\",
\"+	c grey30\",
\"@	c grey40\",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"     .........              \",
\"     .XXXXXXX..             \",
\"     .XXXXXXX...            \",
\"     .X.....X....oooooo     \",
\"     .XXXXXXXXXX.oooooooo   \",
\"     .X....XXXXX.ooooooooo  \",
\"     .XXXXXXXXXX.ooooooooO  \",
\"     .XXXXX.........ooo+OO  \",
\"     .X..XX.XXXXXXX..+++OO  \",
\"     .XXXXX.XXXXXXX...++OO  \",
\"     .XXXXX.X.....X....+OO  \",
\"     .XXXXX.XXXXXXXXXX.+OO  \",
\"     .XXXXX.X....XXXXX.+OO  \",
\"     .......XXXXXXXXXX.+OO  \",
\"           .XXXXXXXXXX.+OO  \",
\"           .X.......XX.+OO  \",
\"           .XXXXXXXXXX.+OO  \",
\"           .XXXXXXXXXX.+OO  \",
\"           .XXXXXXXXXX.+OO  \",
\"           .XXXXXXXXXX.+OO  \",
\"           ............+O   \",
\"                 o@@@++     \",
\"                            \",
\"                            \"};
")
  "A copy icon list.")

(defvar sql-paste-icon
  (toolbar-make-button-list "/* XPM */
static char * sql-paste-red_xpm[] = {
\"28 28 10 1\",
\" 	s backgroundToolBarColor	c Gray75\",
\".	c black\",
\"X	c Gray90\",
\"o	c Gray60\",
\"O	c grey50\",
\"+	c grey65\",
\"@	c grey30\",
\"#	c grey40\",
\"$	c red\",
\"%	c white\",
\"                            \",
\"                            \",
\"                            \",
\"             ..             \",
\"            .XX.            \",
\"      ......X..X......      \",
\"     .oooo.XXXXXX.oooo.     \",
\"     .ooo........OOOOOOO    \",
\"     .oooooooooOOOOOOOOOO   \",
\"     .ooooooooOOOOOOOOOOOO  \",
\"     .oooooooo+OOOOOOOOOO.  \",
\"     .oooooooo++OOOOOOO@..  \",
\"     .oooooooo++OO###@@@..  \",
\"     .oooooo$$$$$$$$$$$@..  \",
\"     .oooooo$%%%%%%%%$$@..  \",
\"     .oooooo$%%%%%%%%$$$..  \",
\"     .oooooo$%$$$$$$%$$$$.  \",
\"     .oooooo$%%%%%%%%%%%$.  \",
\"     .oooooo$%$$$$%%%%%%$.  \",
\"     .oooooo$%%%%%%%%%%%$.  \",
\"     .oooooo$%%%%%%%%%%%$.  \",
\"     .oooooo$%$$$$$$$$%%$.  \",
\"     .......$%%%%%%%%%%%$.  \",
\"            $%%%%%%%%%%%$.  \",
\"            $%%%%%%%%%%%$   \",
\"            $$$$$$$$$$$$$   \",
\"                            \",
\"                            \"};
")
  "A paste icon list.")

(defvar sql-delete-icon
  (toolbar-make-button-list "/* XPM */
static char * sql-delete_xpm[] = {
\"28 28 7 1\",
\" 	s backgroundToolBarColor	c Gray75\",
\".	c red\",
\"X	c grey50\",
\"o	c black\",
\"O	c grey30\",
\"+	c grey40\",
\"@	c grey65\",
\"                            \",
\"                            \",
\"             ..             \",
\"            .  .            \",
\"            .  .            \",
\"      ................      \",
\"      ................      \",
\"      ................XX    \",
\"                     XXXX   \",
\"        ............XXXXXX  \",
\"        ............XXXXXo  \",
\"        ............XXXOoo  \",
\"        ... .... ...+OOOoo  \",
\"        ... .... ...+OOOoo  \",
\"        ... .... ...+OOOoo  \",
\"        ... .... ...+OOOoo  \",
\"        ... .... ...+OOOoo  \",
\"        ... .... ...+OOOoo  \",
\"        ... .... ...+OOOoo  \",
\"        ... .... ...+OOOoo  \",
\"        ............+OOOoo  \",
\"        ............+OOOoo  \",
\"        ............+OOOoo  \",
\"        ............+OOOoo  \",
\"               @XX+++OOOo   \",
\"                 X+++OO     \",
\"                            \",
\"                            \"};
")
  "A delete icon list.")

(defvar sql-insert-icon
  (toolbar-make-button-list "/* XPM */
static char * sql-insert_xpm[] = {
\"28 28 7 1\",
\" 	s backgroundToolBarColor	c Gray75\",
\".	c red\",
\"X	c grey50\",
\"o	c black\",
\"O	c grey40\",
\"+	c grey30\",
\"@	c grey65\",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"           .......          \",
\"           .......          \",
\"           .......          \",
\"           .......XXXXX     \",
\"           .......XXXXXXX   \",
\"           .......XXXXXXXX  \",
\"           .......XXXXXXXo  \",
\"    .....................o  \",
\"    .....................o  \",
\"    .....................o  \",
\"    .....................o  \",
\"    .....................o  \",
\"    .....................o  \",
\"           .......OOO+++oo  \",
\"           .......OOO+++oo  \",
\"           .......OOO+++oo  \",
\"           .......OOO+++oo  \",
\"           .......OOO+++oo  \",
\"           .......OOO+++oo  \",
\"           .......OOO+++oo  \",
\"               @XXOOO+++o   \",
\"                 XOOO++     \",
\"                            \",
\"                            \"};
")
  "An insert icon list.")

;; FIXME!!!!!!!!!!
(defvar sql-frame-icon
  (make-image-instance "/* XPM */
static char * sql-insert_xpm[] = {
\"28 28 7 1\",
\" 	s backgroundToolBarColor	c Gray75\",
\".	c red\",
\"X	c grey50\",
\"o	c black\",
\"O	c grey40\",
\"+	c grey30\",
\"@	c grey65\",
\"                            \",
\"                            \",
\"                            \",
\"                            \",
\"           .......          \",
\"           .......          \",
\"           .......          \",
\"           .......XXXXX     \",
\"           .......XXXXXXX   \",
\"           .......XXXXXXXX  \",
\"           .......XXXXXXXo  \",
\"    .....................o  \",
\"    .....................o  \",
\"    .....................o  \",
\"    .....................o  \",
\"    .....................o  \",
\"    .....................o  \",
\"           .......OOO+++oo  \",
\"           .......OOO+++oo  \",
\"           .......OOO+++oo  \",
\"           .......OOO+++oo  \",
\"           .......OOO+++oo  \",
\"           .......OOO+++oo  \",
\"           .......OOO+++oo  \",
\"               @XXOOO+++o   \",
\"                 XOOO++     \",
\"                            \",
\"                            \"};
"))

;(defvar sql--icon
;  (toolbar-make-button-list "")
;  "A  icon list.")

(provide 'sql-icons)
