//
// Generated by JTB 1.2.1
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * multiplicativeExpression -> MultiplicativeExpression()
 * nodeListOptional -> ( ( "+" | "-" ) MultiplicativeExpression() )*
 * </PRE>
 */
public class AdditiveExpression implements Node {
   private Node parent;
   public MultiplicativeExpression multiplicativeExpression;
   public NodeListOptional nodeListOptional;

   public AdditiveExpression(MultiplicativeExpression n0, NodeListOptional n1) {
      multiplicativeExpression = n0;
      if ( multiplicativeExpression != null ) multiplicativeExpression.setParent(this);
      nodeListOptional = n1;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

