//
// Generated by JTB 1.2.1
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * equalityExpression -> EqualityExpression()
 * nodeListOptional -> ( "&" EqualityExpression() )*
 * </PRE>
 */
public class AndExpression implements Node {
   private Node parent;
   public EqualityExpression equalityExpression;
   public NodeListOptional nodeListOptional;

   public AndExpression(EqualityExpression n0, NodeListOptional n1) {
      equalityExpression = n0;
      if ( equalityExpression != null ) equalityExpression.setParent(this);
      nodeListOptional = n1;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

