//
// Generated by JTB 1.2.1
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * expression -> Expression()
 * nodeListOptional -> ( "," Expression() )*
 * </PRE>
 */
public class ArgumentList implements Node {
   private Node parent;
   public Expression expression;
   public NodeListOptional nodeListOptional;

   public ArgumentList(Expression n0, NodeListOptional n1) {
      expression = n0;
      if ( expression != null ) expression.setParent(this);
      nodeListOptional = n1;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

