//
// Generated by JTB 1.2.1
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * conditionalOrExpression -> ConditionalOrExpression()
 * nodeOptional -> [ "?" Expression() ":" ConditionalExpression() ]
 * </PRE>
 */
public class ConditionalExpression implements Node {
   private Node parent;
   public ConditionalOrExpression conditionalOrExpression;
   public NodeOptional nodeOptional;

   public ConditionalExpression(ConditionalOrExpression n0, NodeOptional n1) {
      conditionalOrExpression = n0;
      if ( conditionalOrExpression != null ) conditionalOrExpression.setParent(this);
      nodeOptional = n1;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

