//
// Generated by JTB 1.2.1
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * conditionalAndExpression -> ConditionalAndExpression()
 * nodeListOptional -> ( "||" ConditionalAndExpression() )*
 * </PRE>
 */
public class ConditionalOrExpression implements Node {
   private Node parent;
   public ConditionalAndExpression conditionalAndExpression;
   public NodeListOptional nodeListOptional;

   public ConditionalOrExpression(ConditionalAndExpression n0, NodeListOptional n1) {
      conditionalAndExpression = n0;
      if ( conditionalAndExpression != null ) conditionalAndExpression.setParent(this);
      nodeListOptional = n1;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

