//
// Generated by JTB 1.2.1
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeOptional -> [ "static" ]
 * block -> Block()
 * </PRE>
 */
public class Initializer implements Node {
   private Node parent;
   public NodeOptional nodeOptional;
   public Block block;

   public Initializer(NodeOptional n0, Block n1) {
      nodeOptional = n0;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
      block = n1;
      if ( block != null ) block.setParent(this);
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

