//
// Generated by JTB 1.2.1
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * relationalExpression -> RelationalExpression()
 * nodeOptional -> [ "instanceof" Type() ]
 * </PRE>
 */
public class InstanceOfExpression implements Node {
   private Node parent;
   public RelationalExpression relationalExpression;
   public NodeOptional nodeOptional;

   public InstanceOfExpression(RelationalExpression n0, NodeOptional n1) {
      relationalExpression = n0;
      if ( relationalExpression != null ) relationalExpression.setParent(this);
      nodeOptional = n1;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

