//
// Generated by JTB 1.2.1
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeListOptional -> ( "abstract" | "public" )*
 * unmodifiedInterfaceDeclaration -> UnmodifiedInterfaceDeclaration()
 * </PRE>
 */
public class InterfaceDeclaration implements Node {
   private Node parent;
   public NodeListOptional nodeListOptional;
   public UnmodifiedInterfaceDeclaration unmodifiedInterfaceDeclaration;

   public InterfaceDeclaration(NodeListOptional n0, UnmodifiedInterfaceDeclaration n1) {
      nodeListOptional = n0;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
      unmodifiedInterfaceDeclaration = n1;
      if ( unmodifiedInterfaceDeclaration != null ) unmodifiedInterfaceDeclaration.setParent(this);
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

