//
// Generated by JTB 1.2.1
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;IDENTIFIER&gt;
 * nodeToken1 -> ":"
 * statement -> Statement()
 * </PRE>
 */
public class LabeledStatement implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public NodeToken nodeToken1;
   public Statement statement;

   public LabeledStatement(NodeToken n0, NodeToken n1, Statement n2) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeToken1 = n1;
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
      statement = n2;
      if ( statement != null ) statement.setParent(this);
   }

   public LabeledStatement(NodeToken n0, Statement n1) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeToken1 = new NodeToken(":");
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
      statement = n1;
      if ( statement != null ) statement.setParent(this);
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

