//
// Generated by JTB 1.2.1
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeOptional -> [ "final" ]
 * type -> Type()
 * variableDeclarator -> VariableDeclarator()
 * nodeListOptional -> ( "," VariableDeclarator() )*
 * </PRE>
 */
public class LocalVariableDeclaration implements Node {
   private Node parent;
   public NodeOptional nodeOptional;
   public Type type;
   public VariableDeclarator variableDeclarator;
   public NodeListOptional nodeListOptional;

   public LocalVariableDeclaration(NodeOptional n0, Type n1, VariableDeclarator n2, NodeListOptional n3) {
      nodeOptional = n0;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
      type = n1;
      if ( type != null ) type.setParent(this);
      variableDeclarator = n2;
      if ( variableDeclarator != null ) variableDeclarator.setParent(this);
      nodeListOptional = n3;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

