//
// Generated by JTB 1.2.1
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeListOptional -> ( "public" | "protected" | "private" | "static" | "abstract" | "final" | "native" | "synchronized" )*
 * resultType -> ResultType()
 * nodeToken -> &lt;IDENTIFIER&gt;
 * nodeToken1 -> "("
 * </PRE>
 */
public class MethodDeclarationLookahead implements Node {
   private Node parent;
   public NodeListOptional nodeListOptional;
   public ResultType resultType;
   public NodeToken nodeToken;
   public NodeToken nodeToken1;

   public MethodDeclarationLookahead(NodeListOptional n0, ResultType n1, NodeToken n2, NodeToken n3) {
      nodeListOptional = n0;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
      resultType = n1;
      if ( resultType != null ) resultType.setParent(this);
      nodeToken = n2;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeToken1 = n3;
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
   }

   public MethodDeclarationLookahead(NodeListOptional n0, ResultType n1, NodeToken n2) {
      nodeListOptional = n0;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
      resultType = n1;
      if ( resultType != null ) resultType.setParent(this);
      nodeToken = n2;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeToken1 = new NodeToken("(");
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

