//
// Generated by JTB 1.2.1
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * unaryExpression -> UnaryExpression()
 * nodeListOptional -> ( ( "*" | "/" | "%" ) UnaryExpression() )*
 * </PRE>
 */
public class MultiplicativeExpression implements Node {
   private Node parent;
   public UnaryExpression unaryExpression;
   public NodeListOptional nodeListOptional;

   public MultiplicativeExpression(UnaryExpression n0, NodeListOptional n1) {
      unaryExpression = n0;
      if ( unaryExpression != null ) unaryExpression.setParent(this);
      nodeListOptional = n1;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

