//
// Generated by JTB 1.2.1
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeListOptional -> ( "static" | "abstract" | "final" | "public" | "protected" | "private" )*
 * unmodifiedClassDeclaration -> UnmodifiedClassDeclaration()
 * </PRE>
 */
public class NestedClassDeclaration implements Node {
   private Node parent;
   public NodeListOptional nodeListOptional;
   public UnmodifiedClassDeclaration unmodifiedClassDeclaration;

   public NestedClassDeclaration(NodeListOptional n0, UnmodifiedClassDeclaration n1) {
      nodeListOptional = n0;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
      unmodifiedClassDeclaration = n1;
      if ( unmodifiedClassDeclaration != null ) unmodifiedClassDeclaration.setParent(this);
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

