//
// Generated by JTB 1.2.1
//

package jde.parser.syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(jde.parser.visitor.Visitor v);
   public Object accept(jde.parser.visitor.ObjectVisitor v, Object argu);

   // It is the responsibility of each implementing class to call
   // setParent() on each of its child Nodes.
   public void setParent(Node n);
   public Node getParent();
}

