//
// Generated by JTB 1.2.1
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * primaryExpression -> PrimaryExpression()
 * nodeOptional -> [ "++" | "--" ]
 * </PRE>
 */
public class PostfixExpression implements Node {
   private Node parent;
   public PrimaryExpression primaryExpression;
   public NodeOptional nodeOptional;

   public PostfixExpression(PrimaryExpression n0, NodeOptional n1) {
      primaryExpression = n0;
      if ( primaryExpression != null ) primaryExpression.setParent(this);
      nodeOptional = n1;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

