//
// Generated by JTB 1.2.1
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * primaryPrefix -> PrimaryPrefix()
 * nodeListOptional -> ( PrimarySuffix() )*
 * </PRE>
 */
public class PrimaryExpression implements Node {
   private Node parent;
   public PrimaryPrefix primaryPrefix;
   public NodeListOptional nodeListOptional;

   public PrimaryExpression(PrimaryPrefix n0, NodeListOptional n1) {
      primaryPrefix = n0;
      if ( primaryPrefix != null ) primaryPrefix.setParent(this);
      nodeListOptional = n1;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

