//
// Generated by JTB 1.2.1
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * shiftExpression -> ShiftExpression()
 * nodeListOptional -> ( ( "&lt;" | "&gt;" | "&lt;=" | "&gt;=" ) ShiftExpression() )*
 * </PRE>
 */
public class RelationalExpression implements Node {
   private Node parent;
   public ShiftExpression shiftExpression;
   public NodeListOptional nodeListOptional;

   public RelationalExpression(ShiftExpression n0, NodeListOptional n1) {
      shiftExpression = n0;
      if ( shiftExpression != null ) shiftExpression.setParent(this);
      nodeListOptional = n1;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

