//
// Generated by JTB 1.2.1
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * additiveExpression -> AdditiveExpression()
 * nodeListOptional -> ( ( "&lt;&lt;" | "&gt;&gt;" | "&gt;&gt;&gt;" ) AdditiveExpression() )*
 * </PRE>
 */
public class ShiftExpression implements Node {
   private Node parent;
   public AdditiveExpression additiveExpression;
   public NodeListOptional nodeListOptional;

   public ShiftExpression(AdditiveExpression n0, NodeListOptional n1) {
      additiveExpression = n0;
      if ( additiveExpression != null ) additiveExpression.setParent(this);
      nodeListOptional = n1;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

