//
// Generated by JTB 1.2.1
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * statementExpression -> StatementExpression()
 * nodeListOptional -> ( "," StatementExpression() )*
 * </PRE>
 */
public class StatementExpressionList implements Node {
   private Node parent;
   public StatementExpression statementExpression;
   public NodeListOptional nodeListOptional;

   public StatementExpressionList(StatementExpression n0, NodeListOptional n1) {
      statementExpression = n0;
      if ( statementExpression != null ) statementExpression.setParent(this);
      nodeListOptional = n1;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

