//
// Generated by JTB 1.2.1
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeChoice -> ( PrimitiveType() | Name() )
 * nodeListOptional -> ( "[" "]" )*
 * </PRE>
 */
public class Type implements Node {
   private Node parent;
   public NodeChoice nodeChoice;
   public NodeListOptional nodeListOptional;

   public Type(NodeChoice n0, NodeListOptional n1) {
      nodeChoice = n0;
      if ( nodeChoice != null ) nodeChoice.setParent(this);
      nodeListOptional = n1;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

