

(jde-set-project-name "jde-debug-interpret")
(jde-set-variables 
 '(jde-gen-session-bean-template (quote ("(jde-wiz-insert-imports-into-buffer (list \"javax.ejb.*\"
\"java.rmi.RemoteException\"))" "(jde-wiz-update-implements-clause \"SessionBean\")" "'> \"public void ejbActivate() throws RemoteException {\"'n> \"}\"'n
'n" "'> \"public void ejbPassivate() throws RemoteException {\"'n> \"}\"'n
'n" "'> \"public void ejbRemove() throws RemoteException {\"'n> \"}\"'n 'n" "'> \"public void setSessionContext(SessionContext ctx) throws
RemoteException {\"" "'n> \"}\"'n 'n" "'> \"public void unsetSessionContext() throws RemoteException {\"'n>
\"}\"'n 'n")))
 '(jde-run-classic-mode-vm nil t)
 '(jde-imenu-include-classdef t)
 '(jde-gen-code-templates (quote (("Get Set Pair" . jde-gen-get-set) ("toString method" . jde-gen-to-string-method) ("Action Listener" . jde-gen-action-listener) ("Window Listener" . jde-gen-window-listener) ("Mouse Listener" . jde-gen-mouse-listener) ("Mouse Motion Listener" . jde-gen-mouse-motion-listener) ("Inner Class" . jde-gen-inner-class))))
 '(jde-gen-cflow-else (quote ("(if (jde-parse-comment-or-quoted-p)" "'(l \"else\")" "'(l > \"else \"" "\"{\" > n> r n" "\"} // end of else\" > n>)" ")")))
 '(jde-make-args "" t)
 '(jde-mode-abbreviations (quote (("ab" . "abstract") ("bo" . "boolean") ("br" . "break") ("by" . "byte") ("byv" . "byvalue") ("cas" . "cast") ("ca" . "catch") ("ch" . "char") ("cl" . "class") ("co" . "const") ("con" . "continue") ("de" . "default") ("dou" . "double") ("el" . "else") ("ex" . "extends") ("fa" . "false") ("fi" . "final") ("fin" . "finally") ("fl" . "float") ("fo" . "for") ("fu" . "future") ("ge" . "generic") ("go" . "goto") ("impl" . "implements") ("impo" . "import") ("ins" . "instanceof") ("in" . "int") ("inte" . "interface") ("lo" . "long") ("na" . "native") ("ne" . "new") ("nu" . "null") ("pa" . "package") ("pri" . "private") ("pro" . "protected") ("pu" . "public") ("re" . "return") ("sh" . "short") ("st" . "static") ("su" . "super") ("sw" . "switch") ("sy" . "synchronized") ("th" . "this") ("thr" . "throw") ("throw" . "throws") ("tra" . "transient") ("tr" . "true") ("vo" . "void") ("vol" . "volatile") ("wh" . "while"))))
 '(jde-imenu-enable t)
 '(jde-compile-option-verbose nil)
 '(jde-db-option-heap-size (quote ((1 . "megabytes") (16 . "megabytes"))))
 '(jde-bug-debugger-host-address "HOMEPC_PAULK")
 '(jde-bug-breakpoint-marker-colors (quote ("red" . "yellow")) t)
 '(jde-gen-buffer-boilerplate (quote ("/*" " * Copyright (c) 2000    Paul Kinnucan" " *" " * $Revision$" " */" "" "package jde.debugger;" "")) t)
 '(jde-bug-raise-frame-p t t)
 '(jde-db-option-application-args nil t)
 '(jde-bug-vm-includes-jpda-p t t)
 '(jde-gen-jfc-app-buffer-template (quote ("\"import java.awt.*;\" 'n" "\"import java.awt.event.*;\" 'n" "\"import com.sun.java.swing.*;\" 'n 'n" "\"/**\" 'n" "\" * \"" "(file-name-nondirectory buffer-file-name) 'n" "\" *\" 'n" "\" *\" 'n" "\" * Created: \" (current-time-string) 'n" "\" *\" 'n" "\" * @author \" (user-full-name) 'n" "\" * @version\" 'n" "\" */\" 'n>" "'n>" "\"public class \"" "(file-name-sans-extension (file-name-nondirectory buffer-file-name))" "\" extends JFrame {\" 'n> 'n>" "\"public \"" "(file-name-sans-extension (file-name-nondirectory buffer-file-name))" "\"() {\" 'n>" "\"super(\\\"\" (P \"Enter app title: \") \"\\\");\" 'n>" "\"setSize(600, 400);\" 'n>" "\"addWindowListener(new WindowAdapter() {\" 'n>" "\"public void windowClosing(WindowEvent e) {System.exit(0);}\" 'n>" "\"public void windowOpened(WindowEvent e) {}});\" 'n>" "\"}\" 'n>" "'n>" "\"public static void main(String[] args) {\" 'n>" "'n>" "(file-name-sans-extension (file-name-nondirectory buffer-file-name))" "\" f = new \"" "(file-name-sans-extension (file-name-nondirectory buffer-file-name))" "\"();\" 'n>" "\"f.show();\" 'n>" "\"}\" 'n> 'n>" "\"} // \"" "(file-name-sans-extension (file-name-nondirectory buffer-file-name))" "'n>")))
 '(jde-bug-key-bindings (quote (("" . jde-bug-step-over) ("" . jde-bug-step-into) ("" . jde-bug-step-out) ("" . jde-bug-continue) ("" . jde-bug-set-breakpoint))) t)
 '(jde-compile-option-nowarn nil)
 '(jde-run-java-vm-w "javaw")
 '(jde-compile-option-encoding nil)
 '(jde-run-option-java-profile (quote (nil . "./java.prof")))
 '(jde-bug-jpda-directory "e:/jpda" t)
 '(jde-read-compile-args nil)
 '(jde-run-java-vm "java")
 '(jde-db-option-verbose (quote (nil nil nil)))
 '(jde-db-read-app-args nil)
 '(jde-run-option-heap-profile (quote (nil "./java.hprof" 5 20 "Allocation objects")))
 '(jde-gen-println (quote ("'&" "\"System.out.println(\" (P \"Print out: \") \");\" 'n>")))
 '(jde-enable-abbrev-mode t t)
 '(jde-gen-cflow-main (quote ("(if (jde-parse-comment-or-quoted-p)" "'(l \"main\")" "'(l > \"public static void main (String[] args) \"" "\"{\" > n> r n" "\"} // end of main ()\" > n>)" ")")))
 '(jde-javadoc-exception-tag-template (quote ("* @exception " type " if an error occurs")))
 '(jde-global-classpath (quote ("e:/jmath/classes" "d:/jde-dev/jde/java/classes" "e:/jpda/lib/jpda.jar")) t)
 '(jde-gen-window-listener-template (quote ("'& (P \"Window name: \")" "\".addWindowListener(new WindowAdapter() {\" 'n>" "\"public void windowActivated(WindowEvent e) {}\" 'n>" "\"public void windowClosed(WindowEvent e) {}\" 'n>" "\"public void windowClosing(WindowEvent e) {System.exit(0);}\" 'n>" "\"public void windowDeactivated(WindowEvent e) {}\" 'n>" "\"public void windowDeiconified(WindowEvent e) {}\" 'n>" "\"public void windowIconified(WindowEvent e) {}\" 'n>" "\"public void windowOpened(WindowEvent e) {}});\" 'n>")))
 '(jde-run-working-directory "")
 '(jde-gen-property-change-support (quote ("'&" "\"protected PropertyChangeSupport pcs =  new PropertyChangeSupport(this);\" 'n>" "\"/**\" 'n>\"* Adds a PropertyChangeListener to the listener list.\" 'n>" "\"* The listener is registered for all properties.\" 'n>" "\"*\" 'n> \"* @param listener The PropertyChangeListener to be added\" 'n> \"*/\" 'n>" "\"public void addPropertyChangeListener(PropertyChangeListener listener) {\" 'n>" "\"pcs.addPropertyChangeListener(listener);\" 'n> \"}\" 'n> 'n>" "\"/**\" 'n>\"* Removes a PropertyChangeListener from the listener list.\" 'n>" "\"* This removes a PropertyChangeListener that was registered for all properties.\" 'n>" "\"*\" 'n> \"* @param listener The PropertyChangeListener to be removed\" 'n> \"*/\" 'n>" "\"public void removePropertyChangeListener(PropertyChangeListener listener) {\" 'n>" "\"pcs.removePropertyChangeListener(listener);\" 'n> \"}\" 'n> 'n>" "\"/**\" 'n>\"* Adds a PropertyChangeListener for a specific property.\" 'n>" "\"* The listener will be invoked only when a call on firePropertyChange\" 'n>" "\"* names that specific property.\" 'n>" "\"*\" 'n> \"* @param propertyName The name of the property to listen on\" 'n>" "\"* @param listener The PropertyChangeListener to be added\" 'n> \"*/\" 'n>" "\"public void addPropertyChangeListener(String propertyName,\" 'n>" "\"PropertyChangeListener listener) {\" 'n>" "\"pcs.addPropertyChangeListener(propertyName, listener);\" 'n> \"}\" 'n> 'n>" "\"/**\" 'n>\"* Removes a PropertyChangeListener for a specific property.\" 'n>" "\"*\" 'n> \"* @param propertyName The name of the property that was listened on\" 'n>" "\"* @param listener The PropertyChangeListener to be removed\" 'n> \"*/\" 'n>" "\"public void removePropertyChangeListener(String propertyName,\" 'n>" "\"PropertyChangeListener listener) {\"  'n>" "\"pcs.removePropertyChangeListener(propertyName, listener);\" 'n> \"}\" 'n> 'n>" "\"/**\" 'n>\"* Reports a bound property update to any registered listeners. \" 'n>" "\"* No event is fired if old and new are equal and non-null.\" 'n>" "\"*\" 'n> \"* @param propertyName The programmatic name of the property that was changed\" 'n>" "\"* @param oldValue The old value of the property\" 'n>" "\"* @param newValue The new value of the property.\" 'n> \"*/\" 'n>" "\"public void firePropertyChange(String propertyName, Object oldValue, Object newValue) {\" 'n>" "\"pcs.firePropertyChange(propertyName, oldValue, newValue);\" 'n> \"}\" 'n> 'n>" "\"/**\" 'n>\"* Reports a bound property update to any registered listeners. \" 'n>" "\"* No event is fired if old and new are equal and non-null.\" 'n>" "\"* This is merely a convenience wrapper around the more general\" 'n>" "\"* firePropertyChange method that takes Object values.\" 'n>" "\"* No event is fired if old and new are equal and non-null.\" 'n>" "\"*\" 'n> \"* @param propertyName The programmatic name of the property that was changed\" 'n>" "\"* @param oldValue The old value of the property\" 'n>" "\"* @param newValue The new value of the property.\" 'n> \"*/\" 'n>" "\"public void firePropertyChange(String propertyName, int oldValue, int newValue) {\" 'n>" "\"pcs.firePropertyChange(propertyName, oldValue, newValue);\" 'n> \"}\" 'n> 'n>" "\"/**\" 'n>\"* Reports a bound property update to any registered listeners. \" 'n>" "\"* No event is fired if old and new are equal and non-null.\" 'n>" "\"* This is merely a convenience wrapper around the more general\" 'n>" "\"* firePropertyChange method that takes Object values.\" 'n>" "\"* No event is fired if old and new are equal and non-null.\" 'n>" "\"*\" 'n> \"* @param propertyName The programmatic name of the property that was changed\" 'n>" "\"* @param oldValue The old value of the property\" 'n>" "\"* @param newValue The new value of the property.\" 'n> \"*/\" 'n>" "\"public void firePropertyChange(String propertyName, boolean oldValue, boolean newValue) {\" 'n>" "\"pcs.firePropertyChange(propertyName, oldValue, newValue);\" 'n> \"}\" 'n> 'n>" "\"/**\" 'n>\"* Fires an existing PropertyChangeEvent to any registered listeners.\" 'n>" "\"* No event is fired if the given event's old and new values are equal and non-null. \" 'n>" "\"*\" 'n> \"* @param evt The PropertyChangeEvent object.\" 'n>\"*/\" 'n>" "\"public void firePropertyChange(PropertyChangeEvent evt) {\" 'n>" "\"pcs.firePropertyChange(evt);\" 'n> \"}\" 'n> 'n>" "\"/**\" 'n>\"* Checks if there are any listeners for a specific property.\" 'n>" "\"*\" 'n> \"* @param evt The PropertyChangeEvent object.\" 'n>" "\"* @return <code>true</code>if there are one or more listeners for the given property\" 'n>" "\"*/\" 'n>" "\"public boolean hasListeners(String propertyName) {\" 'n>" "\"return pcs.hasListeners(propertyName);\" 'n> \"}\" 'n> 'n>")))
 '(jde-javadoc-describe-interface-template (quote ("* Describe interface " (jde-javadoc-code name) " here.")))
 '(jde-javadoc-see-tag-template (quote ("* @see " ref)))
 '(jde-imenu-include-signature t)
 '(jde-db-marker-regexp "^Breakpoint hit: .*(\\([^$]*\\).*:\\([0-9]*\\))")
 '(jde-gen-mouse-motion-listener-template (quote ("'& (P \"Component name: \")" "\".addMouseMotionListener(new MouseMotionAdapter() {\" 'n>" "\"public void mouseDragged(MouseEvent e) {}\" 'n>" "\"public void mouseMoved(MouseEvent e) {}});\" 'n>")))
 '(jde-key-bindings (quote (("[? ? ?]" . jde-run-menu-run-applet) ("[? ? ?]" . jde-build) ("[? ? ?]" . jde-compile) ("[? ? ?]" . jde-debug) ("[? ? ?]" . jde-wiz-implement-interface) ("[? ? ?j]" . jde-javadoc-generate-javadoc-template) ("[? ? ?]" . bsh) ("[? ? ?]" . jde-gen-println) ("[? ? ?]" . jde-browse-jdk-doc) ("[? ? ?]" . jde-save-project) ("[? ? ?]" . jde-wiz-update-class-list) ("[? ? ?]" . jde-run) ("[? ? ?]" . speedbar-frame-mode) ("[? ? ?]" . jde-db-menu-debug-applet) ("[? ? ?]" . jde-help-symbol) ("[? ? ?]" . jde-show-class-source) ("[? ? ?]" . jde-wiz-find-and-import) ("[(control c) (control v) (control ?.)]" . jde-complete-at-point-menu) ("[(control c) (control v) ?.]" . jde-complete-at-point))))
 '(jde-gen-cflow-for-i (quote ("(if (jde-parse-comment-or-quoted-p)" "'(l \"fori\")" "'(l > \"for (int \" (p \"variable: \" var) \" = 0; \"" "(s var)" "\" < \"(p \"upper bound: \" ub)\"; \" (s var) \"++) \"" "\"{\" > n> r n" "\"} // end of for (int \" (s var) \" = 0; \"" "(s var) \" < \" (s ub) \"; \" (s var) \"++)\" > n>)" ")")))
 '(jde-run-option-classpath nil t)
 '(jde-javadoc-param-tag-template (quote ("* @param " name " " (jde-javadoc-a type) " " (jde-javadoc-code type) " value")))
 '(jde-compile-option-verbose-path nil)
 '(jde-db-debugger (quote ("jdebug" . "Class")) t)
 '(jde-jdk-doc-url "e:/jdk1.2/docs/index.html" t)
 '(jde-compiler "javac" t)
 '(jde-javadoc-describe-method-template (quote ("* Describe " (jde-javadoc-code name) " method here.")))
 '(jde-gen-class-buffer-template (quote ("(funcall jde-gen-boilerplate-function) 'n" "\"/**\" 'n" "\" * \"" "(file-name-nondirectory buffer-file-name) 'n" "\" *\" 'n" "\" *\" 'n" "\" * Created: \" (current-time-string) 'n" "\" *\" 'n" "\" * @author Paul Kinnucan\" 'n" "\" * @version $Revision$\" 'n" "\" */\" 'n>" "'n>" "\"public class \"" "(file-name-sans-extension (file-name-nondirectory buffer-file-name))" "\" \" (jde-gen-get-super-class) \" {\" 'n> 'n>" "\"public \"" "(file-name-sans-extension (file-name-nondirectory buffer-file-name))" "\"() {\" 'n>" "\"        \" 'n>" "\"}\" 'n>" "'n>" "\"} // \"" "(file-name-sans-extension (file-name-nondirectory buffer-file-name))" "'n>" "\"/*\" 'n" "\" * $Log$\" 'n" "\" */\" 'n" "'n>" "\"// End of \" " "(file-name-nondirectory buffer-file-name)")) t)
 '(jde-appletviewer-option-vm-args nil)
 '(jde-run-executable-args nil)
 '(jde-db-option-garbage-collection (quote (t t)))
 '(jde-use-font-lock t)
 '(jde-compile-option-bootclasspath nil)
 '(jde-make-program "make")
 '(jde-run-option-vm-args nil t)
 '(jde-compile-option-directory "d:/jde-dev/jde/java/classes" t)
 '(jde-wiz-insert-excluded-packages-regexp "bsh.*")
 '(jde-gen-console-buffer-template (quote ("\"/**\" 'n" "\" * \"" "(file-name-nondirectory buffer-file-name) 'n" "\" *\" 'n" "\" *\" 'n" "\" * Created: \" (current-time-string) 'n" "\" *\" 'n" "\" * @author \" (user-full-name) 'n" "\" * @version\" 'n" "\" */\" 'n>" "'n>" "\"public class \"" "(file-name-sans-extension (file-name-nondirectory buffer-file-name))" "\" {\" 'n> 'n>" "\"public \"" "(file-name-sans-extension (file-name-nondirectory buffer-file-name))" "\"() {\" 'n>" "'n>" "\"}\" 'n>" "'n>" "\"public static void main(String[] args) {\" 'n>" "\"        \" 'n>" "\"}\" 'n> 'n>" "\"} // \"" "(file-name-sans-extension (file-name-nondirectory buffer-file-name))" "'n>")))
 '(jde-read-make-args nil)
 '(jde-gen-mouse-listener-template (quote ("'& (P \"Component name: \")" "\".addMouseListener(new MouseAdapter() {\" 'n>" "\"public void mouseClicked(MouseEvent e) {}\" 'n>" "\"public void mouseEntered(MouseEvent e) {}\" 'n>" "\"public void mouseExited(MouseEvent e) {}\" 'n>" "\"public void mousePressed(MouseEvent e) {}\" 'n>" "\"public void mouseReleased(MouseEvent e) {}});\" 'n>")))
 '(jde-run-option-application-args nil t)
 '(jde-bug-vm-executable (quote ("javaw")))
 '(jde-db-set-initial-breakpoint t)
 '(jde-bug-debugger-command-timeout 10 t)
 '(jde-db-option-stack-size (quote ((128 . "kilobytes") (400 . "kilobytes"))))
 '(jde-db-option-properties nil t)
 '(jde-db-source-directories (quote ("d:/jde-dev/jde/java/src/" "e:/jdk1.3/src/" "e:/jmath/src/")) t)
 '(jde-run-read-app-args nil t)
 '(jde-gen-to-string-method-template (quote ("'&" "\"publics String toString() {\" 'n>" "\"return super.toString()\" 'n>" "\"}\" 'n>")))
 '(jde-quote-classpath t)
 '(jde-bug-window-message nil)
 '(jde-build-use-make nil t)
 '(jde-javadoc-author-tag-template (quote ("* @author \"" user-full-name "\" <" user-mail-address ">")))
 '(jde-javadoc-describe-field-template (quote ("* Describe " (jde-javadoc-field-type modifiers) " " (jde-javadoc-code name) " here.")))
 '(jde-compile-option-classpath (quote ("d:/jde-dev/jde/java/classes" "d:/jde-dev/jde/java/src" "e:/jdk1.3/lib/tools.jar" "e:/jdk1.3/jre/lib/rt.jar")) t)
 '(jde-bug-jdk-directory "e:/jdk1.3/")
 '(jde-gen-boilerplate-function (quote jde-gen-create-buffer-boilerplate))
 '(jde-gen-entity-bean-template (quote ("(jde-wiz-insert-imports-into-buffer (list \"javax.ejb.*\"
\"java.rmi.RemoteException\"))" "(jde-wiz-update-implements-clause \"EntityBean\")" "'> \"public void ejbActivate() throws RemoteException {\"'n> \"}\"'n
'n" "'> \"public void ejbPassivate() throws RemoteException {\"'n> \"}\"'n
'n" "'> \"public void ejbLoad() throws RemoteException {\"'n>\"}\"'n 'n" "'> \"public void ejbStore() throws RemoteException {\"'n>\"}\"'n 'n" "'> \"public void ejbRemove() throws RemoteException {\"'n>\"}\"'n 'n" "'> \"public void setEntityContext(EntityContext ctx) throws
RemoteException {\"" "'n>\"}\"'n 'n" "'> \"public void unsetEntityContext() throws RemoteException {\"'n>
\"}\"'n> 'n")))
 '(jde-javadoc-version-tag-template (quote ("* @version 1.0")))
 '(jde-javadoc-describe-constructor-template (quote ("* Creates a new " (jde-javadoc-code name) " instance.")))
 '(jde-bug-server-shmem-name (quote (t . "JDEbug")))
 '(jde-db-startup-commands nil)
 '(jde-compile-option-deprecation nil)
 '(jde-gen-k&r nil t)
 '(jde-db-option-classpath nil t)
 '(jde-gen-cflow-for (quote ("(if (jde-parse-comment-or-quoted-p)" "'(l \"for\")" "'(l > \"for (\" (p \"for-clause: \" clause) \") \"" "\"{\" > n> r n" "\"} // end of for (\" (s clause) \")\" > n>)" ")")))
 '(jde-run-mode-hook nil)
 '(jde-db-option-verify (quote (nil t)))
 '(jde-compile-option-extdirs nil)
 '(jde-imenu-sort nil)
 '(jde-gen-get-set-var-template (quote ("'& (P \"Variable type: \" type) \" \"" "(P \"Variable name: \" name) \";\" 'n> 'n>" "\"/**\" 'n>" "\"* Get the value of \" (s name) \".\" 'n>" "\"* @return Value of \" (s name) \".\" 'n>" "\"*/\" 'n>" "\"public \" (s type) \" get\" (capitalize (jde-gen-lookup-named 'name))" "\"() {return \" (s name) \";}\" 'n> 'n>" "\"/**\" 'n>" "\"* Set the value of \" (s name) \".\" 'n>" "\"* @param v  Value to assign to \" (s name) \".\" 'n>" "\"*/\" 'n>" "\"public void set\" (capitalize (jde-gen-lookup-named 'name))" "\"(\" (s type) \"  v) {this.\" (s name) \" = v;}\" 'n>")))
 '(jde-bug-saved-breakpoints (quote (("jmath.LinearSystem" . 41))) t)
 '(jde-compile-option-sourcepath nil t)
 '(jde-gen-cflow-if (quote ("(if (jde-parse-comment-or-quoted-p)" "'(l \"if\")" "'(l > \"if (\" (p \"if-clause: \" clause) \") \"" "\"{\" > n> r n" "\"} // end of if (\" (s clause) \")\" > n>)" ")")))
 '(jde-db-option-java-profile (quote (nil . "./java.prof")))
 '(jde-compile-option-depend-switch (quote ("-Xdepend")))
 '(jde-run-applet-doc "index.html")
 '(jde-compile-option-vm-args nil)
 '(jde-run-option-garbage-collection (quote (t t)))
 '(jde-db-mode-hook nil)
 '(jde-db-option-heap-profile (quote (nil "./java.hprof" 5 20 "Allocation objects")))
 '(jde-db-read-vm-args nil)
 '(jde-bug-debug nil t)
 '(jde-gen-cflow-if-else (quote ("(if (jde-parse-comment-or-quoted-p)" "'(l \"ife\")" "'(l > \"if (\" (p \"if-clause: \" clause) \") \"" "\"{\" > n> r n" "\"} // end of if (\" (s clause) \")\" > n>" "> \"else \"" "\"{\" > n> r n" "\"} // end of if (\" (s clause) \")else\" > n>)" ")")))
 '(jde-gen-cflow-while (quote ("(if (jde-parse-comment-or-quoted-p)" "'(l \"while\")" "'(l > \"while (\" (p \"while-clause: \" clause) \") \"" "\"{\" > n> r n" "\"} // end of while (\" (s clause) \")\" > n>)" ")")))
 '(jde-bug-server-socket (quote (t . "2112")))
 '(jde-appletviewer-option-encoding "")
 '(jde-bug-breakpoint-cursor-colors (quote ("cyan" . "brown")))
 '(jde-compile-option-target (quote ("1.1")))
 '(jde-run-executable "")
 '(jde-run-option-heap-size (quote ((1 . "megabytes") (16 . "megabytes"))))
 '(jde-gen-cflow-switch (quote ("(if (jde-parse-comment-or-quoted-p)" "'(l \"switch\")" "'(l > \"switch (\" (p \"switch-condition: \" clause) \") \"" "\"{\" > n" "\"case \" (p \"first value: \") \":\" > n> p n" "\"break;\" > n> p n" "\"default:\" > n> p n" "\"break;\" > n" "\"} // end of switch (\" (s clause) \")\" > n>)" ")")))
 '(jde-db-option-vm-args nil)
 '(jde-run-application-class "jde.debugger.interpret.JavaParser" t)
 '(jde-run-option-verbose (quote (nil nil nil)))
 '(jde-project-file-name "prj.el")
 '(jde-compile-option-debug (quote ("all" (t nil nil))) t)
 '(jde-bug-jre-home "")
 '(jde-run-applet-viewer "appletviewer")
 '(jde-entering-java-buffer-hooks (quote (jde-reload-project-file)))
 '(jde-javadoc-return-tag-template (quote ("* @return " (jde-javadoc-a type) " " (jde-javadoc-code type) " value")))
 '(jde-run-read-vm-args nil t)
 '(jde-help-docsets (quote (("javadoc" "e:/jdk1.3/docs/api/" nil) ("javadoc" "d:/jdebug/doc/" nil) ("javadoc" "e:/jpda/doc/jdi/" nil))) t)
 '(jde-javadoc-since-tag-template (quote ("* @since 1.0")))
 '(jde-gen-inner-class-template (quote ("'& \"class \" (P \"Class name: \" class)" "(P \"Superclass: \" super t)" "(let ((parent (jde-gen-lookup-named 'super)))" "(if (not (string= parent \"\"))" "(concat \" extends \" parent))) \" {\" 'n>" "\"public \" (s class) \"() {\" 'n> \"}\" 'n> \"}\" 'n>")))
 '(jde-run-option-verify (quote (nil t)))
 '(jde-compile-option-optimize nil)
 '(jde-gen-cflow-case (quote ("(if (jde-parse-comment-or-quoted-p)" "'(l \"case\")" "'(l n \"case \" (p \"value: \") \":\" > n> p n" "\"break;\" > n> p)" ")")))
 '(jde-compile-option-depend nil)
 '(jde-javadoc-describe-class-template (quote ("* Describe class " (jde-javadoc-code name) " here.")))
 '(jde-gen-action-listener-template (quote ("'& (P \"Component name: \")" "\".addActionListener(new ActionListener() {\" 'n>" "\"public void actionPerformed(ActionEvent e) {\" 'n>" "\"}});\" 'n>")))
 '(jde-compile-option-command-line-args "" t)
 '(jde-gen-buffer-templates (quote (("Class" . jde-gen-class) ("Console" . jde-gen-console) ("Swing App" . jde-gen-jfc-app))))
 '(jde-project-context-switching-enabled-p t)
 '(jde-run-option-stack-size (quote ((128 . "kilobytes") (400 . "kilobytes"))))
 '(jde-run-option-properties nil t))

