//
// Generated by JTB 1.2.1
//

package jde.debugger.interpret.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * multiplicativeExpression -> MultiplicativeExpression()
 * nodeListOptional -> ( ( "+" | "-" ) MultiplicativeExpression() )*
 * </PRE>
 */
public class AdditiveExpression implements Node {
   public MultiplicativeExpression multiplicativeExpression;
   public NodeListOptional nodeListOptional;

   public AdditiveExpression(MultiplicativeExpression n0, NodeListOptional n1) {
      multiplicativeExpression = n0;
      nodeListOptional = n1;
   }

   public void accept(jde.debugger.interpret.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.debugger.interpret.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

