//
// Generated by JTB 1.2.1
//

package jde.debugger.interpret.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * equalityExpression -> EqualityExpression()
 * nodeListOptional -> ( "&" EqualityExpression() )*
 * </PRE>
 */
public class AndExpression implements Node {
   public EqualityExpression equalityExpression;
   public NodeListOptional nodeListOptional;

   public AndExpression(EqualityExpression n0, NodeListOptional n1) {
      equalityExpression = n0;
      nodeListOptional = n1;
   }

   public void accept(jde.debugger.interpret.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.debugger.interpret.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

