//
// Generated by JTB 1.2.1
//

package jde.debugger.interpret.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> "("
 * nodeOptional -> [ ArgumentList() ]
 * nodeToken1 -> ")"
 * </PRE>
 */
public class Arguments implements Node {
   public NodeToken nodeToken;
   public NodeOptional nodeOptional;
   public NodeToken nodeToken1;

   public Arguments(NodeToken n0, NodeOptional n1, NodeToken n2) {
      nodeToken = n0;
      nodeOptional = n1;
      nodeToken1 = n2;
   }

   public Arguments(NodeOptional n0) {
      nodeToken = new NodeToken("(");
      nodeOptional = n0;
      nodeToken1 = new NodeToken(")");
   }

   public void accept(jde.debugger.interpret.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.debugger.interpret.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

