//
// Generated by JTB 1.2.1
//

package jde.debugger.interpret.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * expression -> Expression()
 * nodeListOptional -> ( "," Expression() )*
 * </PRE>
 */
public class ArgumentList implements Node {
   public Expression expression;
   public NodeListOptional nodeListOptional;

   public ArgumentList(Expression n0, NodeListOptional n1) {
      expression = n0;
      nodeListOptional = n1;
   }

   public void accept(jde.debugger.interpret.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.debugger.interpret.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

