//
// Generated by JTB 1.2.1
//

package jde.debugger.interpret.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeList -> ( "[" Expression() "]" )+
 * nodeListOptional -> ( "[" "]" )*
 * </PRE>
 */
public class ArrayDimsAndInits implements Node {
   public NodeList nodeList;
   public NodeListOptional nodeListOptional;

   public ArrayDimsAndInits(NodeList n0, NodeListOptional n1) {
      nodeList = n0;
      nodeListOptional = n1;
   }

   public void accept(jde.debugger.interpret.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.debugger.interpret.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

