//
// Generated by JTB 1.2.1
//

package jde.debugger.interpret.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * inclusiveOrExpression -> InclusiveOrExpression()
 * nodeListOptional -> ( "&&" InclusiveOrExpression() )*
 * </PRE>
 */
public class ConditionalAndExpression implements Node {
   public InclusiveOrExpression inclusiveOrExpression;
   public NodeListOptional nodeListOptional;

   public ConditionalAndExpression(InclusiveOrExpression n0, NodeListOptional n1) {
      inclusiveOrExpression = n0;
      nodeListOptional = n1;
   }

   public void accept(jde.debugger.interpret.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.debugger.interpret.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

