//
// Generated by JTB 1.2.1
//

package jde.debugger.interpret.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * conditionalAndExpression -> ConditionalAndExpression()
 * nodeListOptional -> ( "||" ConditionalAndExpression() )*
 * </PRE>
 */
public class ConditionalOrExpression implements Node {
   public ConditionalAndExpression conditionalAndExpression;
   public NodeListOptional nodeListOptional;

   public ConditionalOrExpression(ConditionalAndExpression n0, NodeListOptional n1) {
      conditionalAndExpression = n0;
      nodeListOptional = n1;
   }

   public void accept(jde.debugger.interpret.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.debugger.interpret.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

