//
// Generated by JTB 1.2.1
//

package jde.debugger.interpret.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * conditionalExpression -> ConditionalExpression()
 * nodeOptional -> [ AssignmentOperator() Expression() ]
 * </PRE>
 */
public class Expression implements Node {
   public ConditionalExpression conditionalExpression;
   public NodeOptional nodeOptional;

   public Expression(ConditionalExpression n0, NodeOptional n1) {
      conditionalExpression = n0;
      nodeOptional = n1;
   }

   public void accept(jde.debugger.interpret.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.debugger.interpret.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

