//
// Generated by JTB 1.2.1
//

package jde.debugger.interpret.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * exclusiveOrExpression -> ExclusiveOrExpression()
 * nodeListOptional -> ( "|" ExclusiveOrExpression() )*
 * </PRE>
 */
public class InclusiveOrExpression implements Node {
   public ExclusiveOrExpression exclusiveOrExpression;
   public NodeListOptional nodeListOptional;

   public InclusiveOrExpression(ExclusiveOrExpression n0, NodeListOptional n1) {
      exclusiveOrExpression = n0;
      nodeListOptional = n1;
   }

   public void accept(jde.debugger.interpret.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.debugger.interpret.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

