//
// Generated by JTB 1.2.1
//

package jde.debugger.interpret.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * relationalExpression -> RelationalExpression()
 * nodeOptional -> [ "instanceof" Type() ]
 * </PRE>
 */
public class InstanceOfExpression implements Node {
   public RelationalExpression relationalExpression;
   public NodeOptional nodeOptional;

   public InstanceOfExpression(RelationalExpression n0, NodeOptional n1) {
      relationalExpression = n0;
      nodeOptional = n1;
   }

   public void accept(jde.debugger.interpret.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.debugger.interpret.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

