//
// Generated by JTB 1.2.1
//

package jde.debugger.interpret.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * unaryExpression -> UnaryExpression()
 * nodeListOptional -> ( ( "*" | "/" | "%" ) UnaryExpression() )*
 * </PRE>
 */
public class MultiplicativeExpression implements Node {
   public UnaryExpression unaryExpression;
   public NodeListOptional nodeListOptional;

   public MultiplicativeExpression(UnaryExpression n0, NodeListOptional n1) {
      unaryExpression = n0;
      nodeListOptional = n1;
   }

   public void accept(jde.debugger.interpret.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.debugger.interpret.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

