//
// Generated by JTB 1.2.1
//

package jde.debugger.interpret.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * name -> Name()
 * nodeListOptional -> ( "," Name() )*
 * </PRE>
 */
public class NameList implements Node {
   public Name name;
   public NodeListOptional nodeListOptional;

   public NameList(Name n0, NodeListOptional n1) {
      name = n0;
      nodeListOptional = n1;
   }

   public void accept(jde.debugger.interpret.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.debugger.interpret.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

