//
// Generated by JTB 1.2.1
//

package jde.debugger.interpret.syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(jde.debugger.interpret.visitor.Visitor v);
   public Object accept(jde.debugger.interpret.visitor.ObjectVisitor v, Object argu);

}

