//
// Generated by JTB 1.2.1
//

package jde.debugger.interpret.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * primaryPrefix -> PrimaryPrefix()
 * nodeListOptional -> ( PrimarySuffix() )*
 * </PRE>
 */
public class PrimaryExpression implements Node {
   public PrimaryPrefix primaryPrefix;
   public NodeListOptional nodeListOptional;

   public PrimaryExpression(PrimaryPrefix n0, NodeListOptional n1) {
      primaryPrefix = n0;
      nodeListOptional = n1;
   }

   public void accept(jde.debugger.interpret.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.debugger.interpret.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

