//
// Generated by JTB 1.2.1
//

package jde.debugger.interpret.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeChoice -> ( PrimitiveType() | Name() )
 * nodeListOptional -> ( "[" "]" )*
 * </PRE>
 */
public class Type implements Node {
   public NodeChoice nodeChoice;
   public NodeListOptional nodeListOptional;

   public Type(NodeChoice n0, NodeListOptional n1) {
      nodeChoice = n0;
      nodeListOptional = n1;
   }

   public void accept(jde.debugger.interpret.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jde.debugger.interpret.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

