;;; zenirc-bork.el --- Swedish Chef message catalog for ZenIRC

;; Copyright (C) 1993, 1994 Ben A. Mesander
;; Copyright (C) 1998 Per Persson

;; Author: Per Persson <pp@sno.pp.se>
;; Maintainer: pp@sno.pp.se
;; Keywords: extensions
;; Created: 95-07-28

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program; if not, you can either send email to this
;; program's maintainer or write to: The Free Software Foundation,
;; Inc.; 675 Massachusetts Avenue; Cambridge, MA 02139, USA.

;;; Commentary:

;;;  "I am Svedish Chef of Burg. Prepaur to bey Assimilatedy."
;;;  "Borg borg borg!"

;;; Code:
(require 'zenirc)

(zenirc-lang-define-catalog
 'bork
 '((s001 . "[inffu] Yuoo ere-a vesteeng teeme-a. Bork Bork Bork!")
   (s002 . "[inffu] Yuoor IRC serfer is %s roonneeng ircd ferseeun %s")
   (s003 . "[inffu] Thees serfer ves creeted %s")
   (s200 . "[inffu] %s (%s) Leenk -> %s")
   (s202 . "[inffu] %s H.S. -> %s")
   (s203 . "[inffu] %s Hmmm -> IP eddress: %s")
   (s204 . "[inffu] %s Oper -> %s")
   (s205 . "[inffu] %s User -> %s")
   (s206 . "[inffu] %s Serf -> %s %s %s %s ")
   (s208 . "[inffu] %s %s -> %s")
   (s209 . "[inffu] %s Cles -> %s = %s")
   (s211 . "[inffu] %s lenk up %s sec\nSent: %s/%s, Rcvd: %s/%s, SendQ: %s")
   (s212 . "[inffu] %s\t->\tteemes: %s\tbytes: %s")
   (s213 . "[inffu] C hst/nme/prt/cls: %s/%s/%s/%s")
   (s214 . "[inffu] N hst/nme/prt/cls: %s/%s/%s/%s")
   (s215 . "[inffu] %s hust/neme-a/cless:\t%s/%s/%s")
   (s216 . "[inffu] K hust/userneme-a:\t%s/%s")
   (s217 . "[inffu] Q %s/%s/%s/%s/%s")
   (s218 . "[inffu] Cless: %s Peeng freq: %s Conn.freq: %s Mex Leenks: %s Sendq: %s")
   (s219 . "[inffu] Ind ooff /stets.")
   (s221 . "[inffu] Yuoor coorrent user mude-a is: %s")
   (s241 . "[inffu] LEEF hustmesk/dept:\t\t%s/%s")
   (s242 . "[inffu] %s")
   (s243 . "[inffu] %s neeckneme-a/user@hust:\t%s/%s")
   (s244 . "[inffu] HOoB  hustmesk/serferneme-a:\t%s/%s")
   (s251 . "[inffu] Zeere-a ere-a %s/%s feesible-a/infeesible-a users oon %s serfers.")
   (s252 . "[inffu] Zeere-a ere-a %s mejur dveebs oonleene-a.")
   (s253 . "[inffu] Zeere-a ere-a %s unknoon cunnecshuns.")
   (s254 . "[inffu] Zeere-a ere-a %s chunnels")
   (s255 . "[inffu] Zeere-a ere-a %s cleeents und %s serfers cunnected tu thees serfer")
   (s256 . "[inffu] Edmeenistretife-a inffurmeshun fur %s:")
   (s257 . "[inffu] %s")
   (s258 . "[inffu] %s")
   (s259 . "[inffu] %s")
   (s261 . "[inffu] %s Feele-a -> %s %s")
   (s301 . "[inffu] %s is evey: %s")
   (s302 . "[inffu] userhust: %s")
   (s303 . "[inffu] Coorrently vesteeng teeme-a: %s")
   (s305 . "[inffu] Yuoo ere-a nu lunger evey")
   (s306 . "[inffu] Yuoo ere-a evey")
   (s311 . "[inffu] %s (%s@%s) is %s")
   (s312 . "[inffu] %s isves useeng serfer %s (%s)")
   (s313 . "[inffu] %s is a mejur dveeb.")
   (s314 . "[inffu] %s (%s@%s) ves %s")
   (s315 . "[inffu] Ind ooff /vhu.")
   (s317 . "[inffu] %s hes beee idle-a %s")
   (s318 . "[inffu] Ind ooff /vhuees.")
   (s319 . "[inffu] %s is on: %s")
   (s321 . "[inffu] Chunnel         Users Tupeec")
   (s322 . "[inffu] %-15s %-5s %s")
   (s323 . "[inffu] Ind ooff /leest.")
   (s324 . "[inffu] Mude-a fur %s is %s %s")
   (s331 . "[inffu] %s hes nu tupeec")
   (s332 . "[inffu] %s tupeec: %s")
   (s333 . "[inffu] %s tupeec set by %s et %s")
   (s341 . "[inffu] Yuoo ere-a infeeting %s tu %s")
   (s342 . "[inffu] Yuoo ere-a eskeeng %s tu veste-a teeme-a")
   (s351 . "[inffu] Ferseeun: %s %s %s")
   (s352_header . "[inffu] Neeckneme-a  Stet Neme-a ooff Chunnel User@hust (Hup cuoont  Neme-a)")
   (s352 . "[inffu] %-9s %-3s  %-15s %s@%s (%s)")
   (s353 . "[inffu] Users on %s: %s")
   (s364 . "[inffu] %s %s %s")      
   (s365 . "[inffu] Ind ooff /leenks")
   (s367 . "[inffu] %s bun %s")     
   (s368 . "[inffu] Ind ooff bunleest")
   (s371 . "[inffu] %s")            
   (s372 . "[motd] %s")		
   (s375 . "[motd] Messege-a Ooff Zee Dey:")
   (s376 . "[motd] End ooff mutd")
   (s381 . "[inffu] You are now a major dweeb")
   (s382 . "[inffu] Rehesheeng: %s")
   (s391 . "[inffu] Teeme-a fur serfer %s: %s")
   (s392 . "[inffu] Usereed  Termeenel  Hust")
   (s393 . "[inffu] %s")
   (s395 . "[inffu] Nubudy lugged oon")
   (s401 . "[inffu] Nu sooch neeck/chunnel: %s")
   (s402 . "[inffu] Nu sooch serfer: %s")
   (s403 . "[inffu] Noo suuch choonnel: %s")
   (s404 . "[inffu] Yuoo cunnut send tu %s.")
   (s405 . "[inffu] Tuu muny chunnels: %s")
   (s406 . "[inffu] Serfer hes nu recurd ooff neeckneme-a: %s")
   (s407 . "[inffu] Doopleecete-a receepients. Nu messege-a sent: %s")
   (s409 . "[inffu] Nu ooreegin speceeffied.")
   (s411 . "[inffu] Nu receepient geefee.")
   (s412 . "[inffu] Nu text tu send.")
   (s413 . "[inffu] Nu tuplefel dumeeen: %s")
   (s414 . "[inffu] Veeldcerd in tuplefel dumeeen: %s")
   (s421 . "[inffu] Thees luuks leeke-a spem tu me-a: %s.  Bork Bork Bork!")
   (s422 . "[inffu] Nu mutd (fleme-a mejur dveeb leested in /edmeen)")
   (s423 . "[inffu] Nu edmeen inffu.  Ignurunt mejur dveeb roonneeng serfer.")
   (s431 . "[inffu] Nu neeckneme-a geefee")
   (s432 . "[inffu] Infeleed neeckneme-a: %s")
   (s433 . "[inffu] Neeckneme-a elreedy in use-a: %s")
   (s436 . "[inffu] Neeck culleesiun keell: %s")
   (s441 . "[inffu] %s is nut oon %s")
   (s442 . "[inffu] Yuoo ere-a nut oon %s.")
   (s443 . "[inffu] %s is elreedy oon chunnel %s.")
   (s444 . "[inffu] %s is nut lugged in")
   (s445 . "[inffu] Sume-a mejur dveeb vun't let yuoo du soommun")
   (s446 . "[inffu] Sume-a mejur dveeb vun't let yuoo du /users")
   (s451 . "[inffu] Yuoo hefe-a nut regeestered")
   (s461 . "[inffu] Nut inuoogh peremeters: %s")
   (s462 . "[inffu] Yuoo mey nut reregeester")
   (s463 . "[inffu] Sume-a fesceest mejur dveeb veell nut let yuoo cunnect")
   (s464 . "[inffu] Pessvurd is incurrect")
   (s465 . "[inffu] Yuoo ere-a nut ellooed tu use-a thees serfer.")
   (s467 . "[inffu] Key fur %s is elreedy set.")
   (s471 . "[inffu] Cunnut jueen %s (user leemit reeched).")
   (s472 . "[inffu] s is un unknoon mude-a cherecter.")
   (s473 . "[inffu] Cunnut jueen %s (infeete-a oonly).")
   (s474 . "[inffu] Cunnut jueen %s (bun).")
   (s475 . "[inffu] Cunnut jueen %s (chunnel key).")
   (s481 . "[inffu] Yuoo ere-a nut a beeg inuoogh dveeb tu du thet.")
   (s482 . "[inffu] Yuoo ere-a nut a pooermunger fur %s.")
   (s483 . "[inffu] Dooh. Yuoo cunnut keell a serfer")
   (s491 . "[inffu] Nu mejur dveebs ellooed frum yuoor hust")
   (s501 . "[inffu] Unknoon user mude-a fleg")
   (s502 . "[inffu] Cunnut chunge-a mude-a fur oozeer users")
   (action . "(sent tu %s)")
   (action-echo . "(sent tu %s)")
   (connect-failed . "[irrur] Cuooldn't cunnect tu %s purt %d, reesun: %s")
   (connect-try . "[inffu] Cunnecteeng tu %s purt %d...")
   (connect-abort . "[inffu] Eburted ettempt tu cunnect tu un irc serfer.")
   (ctcp_action . "[ecshun->%s] %s %s") ; ctcp ACTION display
   (ctcp_clientinffu . "[qooery] CLIENTINFO frum %s tu %s")
   (ctcp_errmsg . "[qooery] IRRMSG frum %s tu %s")
   (ctcp_finger . "[qooery] FINGER frum %s tu %s")
   (ctcp_ping . "[qooery] PING frum %s tu %s")
   (ctcp_ping_reply . "[reply] PING: %s is %s secunds evey")
   (ctcp_source . "[qooery] SOOoRCE frum %s tu %s")
   (ctcp_time . "[qooery] TIME frum %s tu %s")
   (ctcp_userinffu . "[qooery] USERINFFU from %s to %s")
   (ctcp_version . "[qooery] FERSION frum %s tu %s")
   (debug  . "[debug] %s")
   (error . "[%s] %s")
   (invite . "[inffu] %s infeetes yuoo tu %s.")
   (join_you . "[inffu] Jueening chunnel: %s")
   (join . "[inffu] %s hes jueened %s")
   (kick . "[inffu] %s hes beee keecked frum %s by %s")
   (kick_you . "[inffu] Yuoo hefe-a beee keecked frum %s by %s")
   (kill . "[inffu] Yuoo hefe-a beee keelled: %s")
   (mode . "[inffu] %s hes chunged mude-a fur %s: %s")
   (nick . "[inffu] %s hes chunged neeck tu %s")
   (newcatalog . "[inffu] Coorrent messege-a cetelug set tu %s")
   (nocatalog . "[error] Nu messege-a cetelug deffeened fur %s")
   (nosend . "[inffu] yuoo hefe-a nu coorrent feectim tu send tu")
   (notice . "{%s%s} %s")
   (notice_you . "{%s} %s")
   (now_qooerying . "[inffu] Coorrent feectim is %s.")
   (part_you . "[inffu] Leefeeng: %s (%s)") ; your part from channel message
   (part . "[inffu] %s hes lefft %s (%s)")
   (pong . "[inffu] %s seys oojnk")
   (privmsg . "<%s%s> %s")
   (privmsg_you . "*%s* %s")
   (protocol_violation . "[irrur] Zee fullooeeng leene-a is in feeuleshun ooff zee IRC prutucul.\n[irrur] Pleese-a tell zee serfer edmeenistretur:\n%s: %s")
   (query . "[qooery] frum %s tu %s cuntent %s")
   (qyery_unknown . "is un unknoon CTCP qooery")
   (query_unbalanced . "[UNBALANCED qooery] um %s tu %s cuntent %s")
   (query_unbalanced_reply . "is un unbelunced CTCP quuery")
   (quit . "[inffu] %s stupped vesteeng teeme-a: %s")
   (reply . "[reply] frum %s tu %s cuntent %s")
   (reply_unbalanced . "[UNBELENCED reply] frum %s tu %s cuntent %s")
   (send . "(sent tu %s)")
   (send-echo . "(sent tu %s)")
   (send-multi . "(sent tu %s in %d perts)")
   (send-multi-echo . "(sent tu %s in %d perts)")
   (sentinel . "\nZenIRC inded et %s")
   (server . "[serfer] %s")
   (signal . "[seegnel in %s]")
   (topic . "[inffu] %s chunged zee tupeec oon %s tu: %s")
   (wallops . "-%s- %s")
   ))

(provide 'zenirc-bork)

;;; zenirc-bork.el ends here
